### PR TITLE
Fix typos for italian translation

### PR DESCRIPTION
**Pull request by romolox**
This is a work in progress, we'll leave it open to sync our work with other contributors

### CODE REVIEW

**Comment by olasitarska** [comment]
Please ping @DjangoGirls/committers when this is ready to be merged :)

**Comment by astagi** [comment]
@olasitarska @tricoder42 we're done with this! :tada:

**Comment by romolox** [comment]
@DjangoGirls/committers we are ready :)

**Comment by romolox** [comment]
@olasitarska we are ready :)

**Comment by astagi** [comment]
@olasitarska @tricoder42 @phalt sorry for our pressure about this PR, but we need to have all the changes we made online within tomorrow, we will start Django Girls Rome at 9.00 o'clock and there are important fixes in the IT translation of the tutorial. Thank you in advance :smile:

**Comment by tricoder42** [comment]
@astagi Absolutely! Sorry for the delay. Thank you for awesome work :+1: You rock! :guitar:

**Comment by astagi** [comment]
Thank you @tricoder42 :smile: no problem for the delay! you rock too! :guitar: :smile:

**Pull request merged**
