### PR TITLE
Wrong variable name displays an error

### PR DESCRIPTION
**Pull request by KunihikoKido**
Changes in this pull request:

- Change to Wrong variable name

`ctiy` looks similar to the actual word `city` if you do not pay enough attention. Actually my co-worker who just started to do tutorial typed  `city` and wondered why it did not show as an error.

### CODE REVIEW

**Comment by magul** [comment]
Hi @KunihikoKido, first of all, thank you for that change.

Can You, please, provide some context here, as I don't understand why `citty` is better than `ctiy`. Both of them can be considered as a typo and will raise the same error.

**Comment by KunihikoKido** [comment]
Hi @magul 

`ctiy` looks similar to the actual word `city` if you do not pay enough attention. Actually my co-worker who just started to do tutorial typed  `city` and wondered why it did not show as an error.haha

**Comment by das-g** [comment]
In the English version of the tutorial, this code block is preceded by some prose that introduces the intent:
> But what if we used the wrong name? Can you guess what would happen? Let's try!

To me, this seems sufficient. If this isn't the case in the Japanese version, maybe the translation needs to be improved regarding these sentences? If possible, I'd like to keep variable names consistent between the translations to various languages.

Thus, I'm voting to decline this PR, i.e. close it without merging it.

**Comment by KunihikoKido** [comment]
OK. I understand.

**Pull request closed without merging**
