### PR TITLE
Translated to pt the images on 'how the internet works'...

### PR DESCRIPTION
**Pull request by rsip22**
and changed the URL to https on the image internet_2.

### CODE REVIEW

**Comment by patjouk** [comment]
Thanks for this PR :sparkles: 
@DjangoGirls/pt-pr can you review it? Thanks!

**Comment by annanda** [comment]
Awesome! :+1:

**Comment by rsip22** [comment]
@annanda Could you approve this PR?

**Comment by patjouk** [comment]
Thanks! :cake:

**Pull request merged**
