### PR TITLE
German version (beta as not proofread yet)

### PR DESCRIPTION
**Pull request by magul**
Current build: https://magul.gitbooks.io/django-girls-tutorial/content/v/3fdcee0bedea8f707ab44f682c9f05f586b66650/de/

### CODE REVIEW

**Comment by magul** [comment]
@das-g You could be also interested.

**Comment by das-g** [comment]
I haven't read all of it, but I guess it's an improvement overall, so let's just merge it and do a new PR after proofreading, I guess?

**Comment by das-g** [comment]
How do I proofread on Crowdin, btw.? I've seen I can vote for or against suggested translations of text snippets. Is that the proofreading process or is proofreading something else only available to certain users?

**Comment by das-g** [comment]
> @das-g You need to be proofreader (I just added You to proofreaders group). There is a "proofreading mode" available for every asset (https://support.crowdin.com/online-editor/)

Thanks! I'll probably look into that this evening.

**Comment by normade** [comment]
@das-g @magul Since its about the translation of the Django2 changes, I would suggest to merge after proofreading has been completed, or lets say at least after double reading the installation and urls chapters. I translated the new parts, but proofread only the already translated "old" parts.

**Comment by chrisfrie** [comment]
@magul Could you add me in Crowdin that I can support to proofread the german version? my username in Crowdin is chrisfrie

**Comment by magul** [comment]
@chrisfrie You need to join project first, then I will be able to add proofreader role to your account.

**Comment by magul** [comment]
Newest build available here: https://magul.gitbooks.io/django-girls-tutorial/content/v/7047d650fcffb3644c63a5ed9d2c87cf54ffa293_2/

**Comment by normade** [comment]
Thank you @magul, its very useful!

**Comment by das-g** [comment]
> Can I suggest to merge it as a beta release

:+1: Please do!

> most probably it's more error prone

You mean "less", don't you? ("error prone" means "likely to exhibit/cause/have (many) errors")

**Comment by magul** [comment]
**less** :)

**Pull request merged**
