### PR TITLE
Updated the tutorial to match the english version

### PR DESCRIPTION
**Pull request by lepaperwan**
**Update the Deploy! chapter to match the PythonAnywhere english version. As such, the domain chapter became obsolete and was removed. Also added the first Installation chapter and resorted the Summary to match the englidh tutorial.**

*Français*: Mise à jour du chapitre Déployer! pour correspondre avec la version anglaise PythonAnywhere. Du coup, le chapitre traitant des noms de domaines étant obsolète, il a été supprimé (comme dans le tutoriel anglais). Ajout du chapitre initial d'Installation et réorganisation du sommaire pour trier les parties dans le même ordre que le tutoriel anglais.

### CODE REVIEW

**Comment by lepaperwan** [comment]
Not sure who can accept pull requests but just in case you're not aware, the DjangoGirls Bordeaux is this Saturday, please don't accept it before then as we'd get a modified tutorial day(s) before the event.

**Comment by patjouk** [comment]
This part is already translated in [crowdin](https://crowdin.com/project/django-girls-tutorial/fr). If you want to change big chunks of the tutorial, use this app :wink: 
More info on the translation process [here](http://translate.djangogirls.org/).

**Comment by lepaperwan** [comment]
Oh nice, didn't know there was a crowdin for it.

I agree that PythonAnywhere is far easier to deploy to. I'll discuss it with the others and if everyone is okay with it, I'll let you know :smile:

**Comment by patjouk** [comment]
awesome :smile_cat:

**Comment by lepaperwan** [comment]
Yep, they all seem to like the idea so if you have the time to update the french tutorial, that'd be great !

**Comment by lepaperwan** [comment]
Closing since this has already been translated.

**Comment by patjouk** [comment]
New translation deployed. Have fun at the workshop tomorrow :rose: :smile_cat:

**Pull request closed without merging**
