### PR TITLE
Fix small typos in django_urls and update its Polish translation

### PR DESCRIPTION
**Pull request by Kwpolska**
Thanks for this awesome tutorial! :smiley_cat: Here are some minor fixes to the URL documentation, and an updated Polish translation.

### CODE REVIEW

**Comment by tricoder42** [comment]
Hi @Kwpolska! Thank you for this, looks awesome! :+1: 

However, we use Crowdin (https://crowdin.com) for management of translations. If you aren't registered there I can send you an invite. Please update translations there. Some folks from Poland are updating translations at the moment, so they will copy-paste your changes.

Thank you very much! :smile:

**Comment by agagata** [comment]
Just wanted to let you know that I updated the following chapter on Crowdin. 

Thanks again for your contribution! ✨

**Comment by Kwpolska** [comment]
Shouldn’t this be documented in the README for this repository?

**Comment by tricoder42** [comment]
@Kwpolska Good point! We should definitely mention it there

**Pull request closed without merging**
