### PR TITLE
Bumped Django version to 1.7.5

### PR DESCRIPTION
**Pull request by MarkusH**

### CODE REVIEW

**Comment by bmispelon** [comment]
Awesome, thanks!

:koala:

**Comment by olasitarska** [comment]
That was fast! :zap:

**Comment by bmispelon** [comment]
typing

**Comment by MarkusH** [comment]
:wink:

**Comment by MarkusH** [comment]
I can open a PR for 1.8 if you want *scnr*

**Comment by olasitarska** [comment]
@MarkusH that would be awesome! We won't merge it until 1.8 is out, but it'd be good to start working on it ;)

**Pull request merged**
