### PR TITLE
fix import include

### PR DESCRIPTION
**Pull request by M-b850**
Changes in this pull request:

- from django.contrib import path, include 
    include isn't in django contrib

### CODE REVIEW

**Comment by das-g** [comment]
Was this pull request closed by accident? If you want it to be considered, please re-open it.

**Comment by M-b850** [comment]
> Was this pull request closed by accident? If you want it to be considered, please re-open it.

Yes, accidentally I closed it.
Thank you.

**Comment by M-b850** [comment]
#1698

**Review by Rahimz — APPROVED** [review]
I've edited it in Crowdin.

**Comment by magul** [comment]
Thanks @Rahimz , @das-g and @M-b850 !

**Pull request merged**
