### PR TITLE
French translation from Crowdin.

### PR DESCRIPTION
**Pull request by magul**
Made by:
* Aboudflish (https://crowdin.com/profile/Aboudflish)
* Anna Warzecha (vi) (https://crowdin.com/profile/aniav)
* ariasuni (https://crowdin.com/profile/ariasuni)
* Aurélie g (https://crowdin.com/profile/aurelieg)
* Babacar Gueye (https://crowdin.com/profile/gueyens11)
* BenjaminRochez (https://crowdin.com/profile/BenjaminRochez)
* Bibiiche (https://crowdin.com/profile/bibiiche)
* braxx (https://crowdin.com/profile/braxx)
* cedricvanrompay (https://crowdin.com/profile/cedricvanrompay)
* cleoqc1124 (https://crowdin.com/profile/cleoqc1124)
* eablonet (https://crowdin.com/profile/eablonet)
* Emmanuelle Delescolle (https://crowdin.com/profile/emma_be)
* Francesca Iannuzzi (https://crowdin.com/profile/fiannuzzi)
* fredtantini (https://crowdin.com/profile/fredtantini)
* Gabriella Denizard (https://crowdin.com/profile/abriella)
* Gabrielle (https://crowdin.com/profile/gbastien1)
* Georges Dubus (https://crowdin.com/profile/madjar)
* Harry Percival (https://crowdin.com/profile/hjwp2)
* jguignie (https://crowdin.com/profile/jguignie)
* JKoehren (https://crowdin.com/profile/JKoehren)
* Joachim Jablon (https://crowdin.com/profile/ewjoachim)
* JPK39 (https://crowdin.com/profile/jonathan.king39)
* Laville Augustin (https://crowdin.com/profile/gustavi)
* leila_be (https://crowdin.com/profile/leila_be)
* lyoz (https://crowdin.com/profile/lyoz)
* MadCath (https://crowdin.com/profile/MadCath)
* magicsquirrel (https://crowdin.com/profile/magicsquirrel)
* Malik Fassi Fihri (https://crowdin.com/profile/malikfassifihri)
* Martin Matusiak (https://crowdin.com/profile/numerodix)
* Mathieu Richardoz (https://crowdin.com/profile/metamatik)
* Morgane (https://crowdin.com/profile/niouby)
* olasitarska (https://crowdin.com/profile/olasitarska)
* Owlkat (https://crowdin.com/profile/Owlkat)
* patjouk (https://crowdin.com/profile/patjouk)
* PERCE-NEIGE (https://crowdin.com/profile/PERCE-NEIGE)
* PoorPockets McNewHold (https://crowdin.com/profile/IfiwFR)
* PetitCanap (https://crowdin.com/profile/PetitCanap)
* razerezar (https://crowdin.com/profile/razerezar)
* rtournem (https://crowdin.com/profile/rtournem)
* Sammy Hannat (https://crowdin.com/profile/sammyhannat7)
* sebastienbarbier (https://crowdin.com/profile/sebastienbarbier)
* sprlye (https://crowdin.com/profile/sprlye)
* Stephane ESTEVE (https://crowdin.com/profile/mezklador)
* svorasane (https://crowdin.com/profile/svorasane)
* Sylvain Chiron (https://crowdin.com/profile/Frigory)
* Sylvain Fankhauser (https://crowdin.com/profile/sephii)
* tom1103 (https://crowdin.com/profile/tom1103)

### CODE REVIEW

**Comment by magul** [comment]
Current build available here: https://magul.gitbooks.io/django-girls-tutorial/content/v/d7bfdd9553378587efe6776247403cc724f07fba/

**Comment by fiannuzzi** [comment]
I made a couple of minor changes (basically corrected my own mistakes) since your pull request. I would suggest, if possible, to make a pull request with the latest version. Cheers

**Comment by magul** [comment]
I do not see any changes in the last 2 days and the changes that I see were already updated here. Can You confirm @fiannuzzi that there's something still missing here?

**Comment by fiannuzzi** [comment]
OK, my changes are from March 19. I didn't realise you updated the changes. By looking at the current build you posted above I'm still seeing the old version with the mistakes, which is why I thought I'd make sure.

**Comment by magul** [comment]
Are You talking about https://magul.gitbooks.io/django-girls-tutorial/content/v/d7bfdd9553378587efe6776247403cc724f07fba/ or about version here on GitHub?

Because I force-pushed your new changes git commit hash changed and newest French version is available here: https://magul.gitbooks.io/django-girls-tutorial/content/v/bbd8fb34d69fa90d20d81a3844e832602cd4eaed/

**Comment by fiannuzzi** [comment]
OK, got it! Yes, we are good then :)

**Comment by magul** [comment]
I assume that's approved and going to merge it now! Thanks, well done!

**Pull request merged**
