### PR TITLE
Some text improvements

### PR DESCRIPTION
**Pull request by lipemorais**

### CODE REVIEW

**Comment by olasitarska** [comment]
@lipemorais would you be able to get someone who speak your language to review these changes and :+1: them here? That would be massively appreciated! :)

**Comment by lipemorais** [comment]
@darlenedms and @pgrangeiro, can help you.

**Comment by olasitarska** [comment]
@darlenedms or @pgrangeiro, could you find 5 minutes to take a look on those changes and let me know if they're correct? :) I'd be really grateful!

**Comment by darlenedms** [comment]
@lipemorais I agree with @annanda suggestions. After that I think it will be great :smile:

**Comment by olasitarska** [comment]
Is there any conclusion here? Would love to get this merged, but it's open for a month now and I don't want to let it go stale :(

**Comment by lipemorais** [comment]
Thank you for remember me. I just make fixes suggested by @annanda.

**Comment by patjouk** [comment]
Perfect! Thanks! :cake:

**Pull request merged**
