### PR TITLE
Migration to Django 3.1

### PR DESCRIPTION
**Pull request by nikhiljohn10**
### Migration updates

> NOTE: This update is only for the English language.

- [x] Update book.json
- [x] Updated Django related python syntax and conventions 
- [x] Updated URL version from 2.2 to 3.1
- [x] Updated filesystem tree and output format

This is a followup from #1678

### CODE REVIEW

**Review by das-g — CHANGES_REQUESTED** [review]
:+1: Changes look good to me.

:heavy_check_mark: all changed URLs still work

Could you squash ca9fbdfff89156350fc119e417515ab8befa1229 into b6aa7e2aef8e770d1bc59a0fd534b8f27a2f08df? They're about the same topic.

**Comment by nikhiljohn10** [comment]
> Could you squash [ca9fbdf](https://github.com/DjangoGirls/tutorial/commit/ca9fbdfff89156350fc119e417515ab8befa1229) into [b6aa7e2](https://github.com/DjangoGirls/tutorial/commit/b6aa7e2aef8e770d1bc59a0fd534b8f27a2f08df)? They're about the same topic.

Done

**Review by das-g — APPROVED** [review]
:+1: All good now.

**Comment by nikhiljohn10** [comment]
@das-g @ekohl Can we start a Github project for the migration to track and recognise what all needed to be done? I am getting some free time to contribute these days.

**Comment by das-g** [comment]
> @das-g @ekohl Can we start a Github project for the migration to track and recognise what all needed to be done? I am getting some free time to contribute these days.

Sounds like a good idea, but I have nearly no experience with GitHub's "project" feature, yet. (I do know Git**Lab**'s issue boards well, though, which seem to work somewhat similar.) Should we choose a specific [board template](https://docs.github.com/en/issues/organizing-your-work-with-project-boards/managing-project-boards/about-project-boards#templates-for-project-boards) when creating the project?

**Comment by nikhiljohn10** [comment]
@das-g I think using "Automated kanban with reviews" template is great. But that would pull all the issues that are not related to Django Migration. So I think it's best to use "Basic kanban" template and add required columns afterwards.

**Comment by das-g** [comment]
I've created https://github.com/DjangoGirls/tutorial/projects/3#card-63578263

Does that look alright? I haven't added any automations.

**Comment by nikhiljohn10** [comment]
@das-g That looks great. Those pre-made cards can be removed. If you can fill up the 'To Do' list with Cards regarding Django 3. So people can take up the tasks and work on them. Because currently, I am confused. I have worked on HTML, bootstrap, git, GitBook, python version, Django version etc. Not sure what all are where. So planning to start over.

**Pull request merged**
