### PR TITLE
simplyfying URL

### PR DESCRIPTION
**Pull request by picibucor**
Changes in this pull request:
URL is simpler

### CODE REVIEW

**Comment by ekohl** [comment]
Isn't this Django 2.0 only? It doesn't appear in the 1.11 docs (which we're currently still using).

If we do accept this change, I'd also have a good look at the regular expressions chapter.

**Comment by tnir** [comment]
I'm curious when this project will move to Django 2.0+ only? 😄

**Comment by ekohl** [comment]
> I'm curious when this project will move to Django 2.0+ only? smile

When someone has time. See https://github.com/DjangoGirls/tutorial/issues/1266 as well. I'd be happy to review but don't have time to rewrite it myself.

**Comment by ekohl** [comment]
This was done as part of https://github.com/DjangoGirls/tutorial/pull/1282

**Pull request closed without merging**
