### PR TITLE
[English] Fix: Templates path

### PR DESCRIPTION
**Pull request by rofi93**
Defined path for templates in settings.py

### CODE REVIEW

**Comment by aniav** [comment]
I am not sure do we actually need to add this? If you have the default setting
```
'APP_DIRS': True,
```
in `TEMPLATES` you don't need to add any paths here.

**Comment by rofi93** [comment]
@aniav It gives `TemplateDoesNotExist` exception if we don't add the path.

**Comment by ekohl** [comment]
Where are you creating the template? The tutorial suggests ```blog/templates/blog/<file>.html``` so the whole ```BASE_DIR/templates``` should not be used if the instructions are followed.

**Comment by rofi93** [comment]
@ekohl I was creating in project directory - `blog/templates/blog/<file.html>`.

**Comment by aniav** [comment]
The tutorial shows the whole path of where to put the templates, they should be in the corresponding app directory, not the whole project directory. This works without adding any paths and we would like to keep it this way and not introduce more complications and additional steps 👣

**Pull request closed without merging**
