### PR TITLE
Fix typo in Chinese translation

### PR DESCRIPTION
**Pull request by hr567**
Changes in this pull request:

- Fix typo in Chinese translation

### CODE REVIEW

**Comment by das-g** [comment]
Hi @hr567

Thank you for your contribution! We maintain translations on Crowdin, so could you make this change on  https://crowdin.com/project/django-girls-tutorial/zh-CN please?

**Comment by hr567** [comment]
Ok, I will to that.

**Comment by hr567** [comment]
I had saved the work on Crowdin. Should this pull request be closed?

**Comment by aniav** [comment]
@hr567 this PR should still be merged but it has to be reviewed by someone from the @DjangoGirls/zh-pr team first 🙏

**Pull request merged**
