### PR TITLE
Persian language improvements.

### PR DESCRIPTION
**Pull request by magul**
Made by:
* Fateme Afzoun (https://crowdin.com/profile/fafzoun)
* rahimz (https://crowdin.com/profile/rahimz)
* xLog1c (https://crowdin.com/profile/xLog1c)

### CODE REVIEW

**Comment by magul** [comment]
@Rahimz (un)fortunately we update part of the English version trying to solve some issue, so Persian coverage dropped. Can you, please, choose appropriate translation for these few not translated yet?

**Comment by Rahimz** [comment]
@magul It's done.

**Comment by magul** [comment]
@Rahimz updated!

**Comment by magul** [comment]
@Rahimz do you want to re-review that? Or should I merge it?

**Comment by magul** [comment]
@Rahimz done!

**Pull request merged**
