### PR TITLE
[Portuguese] Fix errors on deploy and start configuration

### PR DESCRIPTION
**Pull request by AmeliaPessoa**

### CODE REVIEW

**Comment by rsip22** [comment]
Mas a implantação no Python Anywhere funciona sem ter de fazer mais aquele acréscimo ao arquivo...

**Comment by AmeliaPessoa** [comment]
These errors were found in a Django Girls in Recife - Brazil today. Without these changes, the code didn`t compile.

**Comment by rsip22** [comment]
Which version of Django were you using? 1.85 or 1.10?

**Comment by AmeliaPessoa** [comment]
Django version 1.10.

**Comment by rsip22** [comment]
Oh, that's why. The portuguese tutorial wasn't adapted to version 1.10 yet. 

With 1.8.5 (the version the pt tutorial says to install), the current instructions work.

Maybe we shouldn't change this until the tutorial is a fully updated to Django 1.10, since further issues might happen?

**Comment by AmeliaPessoa** [comment]
We can use this opportunity to upgrade the version. I can review the tutorial to search more occurrences. Do you prefer to keep the 1.8.5 version?

**Comment by rsip22** [comment]
It would be better if we brought it up to date with the English tutorial (1.10, I believe).

**Comment by rsip22** [comment]
Hopefully everything will work with the changed that were made today.

Thanks for your contribution, @AmeliaPessoa !

**Pull request merged**
