### PR TITLE
Add sectionx and use in installation instructions

### PR DESCRIPTION
**Pull request by delenamalan**
Use the `sectionx` extension to put instructions for different operating systems in separate sections to address #862 .

Started with the Python installation instructions to show what it might look like.

Example of Python installation instructions in separate sections.

Add `sectionx` to:
- [x] Chromebook setup.
- [x] Python installation.
- [x] Virtualenv usage.
- [x] Django installation.
- [x] Git installation.

### CODE REVIEW

**Comment by aniav** [comment]
Awesome job! Do you want this to be merged now or would you like to make some more changes using this extension before merging? :)

**Comment by delenamalan** [comment]
Thanks! I will make some more changes before merging. I'll use the extension for the other installation instructions as well. :)

**Comment by delenamalan** [comment]
All right, @aniav , I think this can be merged.

Good to know, the pdf generated from the book is still fine after using `sectionx`:
Screenshot of pdf generated after sectionx was used.

**Comment by patjouk** [comment]
Thanks a lot for this PR! Your changes are now live and they look awesome! :sparkles:

**Pull request merged**
