### PR TITLE
Spelling and style mistakes corrected

### PR DESCRIPTION
**Pull request by ivigilm**
Changes in this pull request:

- Spelling mistakes
- Puntuaction mistakes
- Style improved

### CODE REVIEW

**Comment by magul** [comment]
Hi @ivigilm,

first of all thanks for your improvements here. We will wait for somebody from Spanis reviewers to do a proper review.

Can you also put them on our Crowdin project (as we tend to maintain translations there and I'm afraid that new sync from Crowdin will overwrite whatever you achieved here).

Link to Crowdin: https://crowdin.com/project/django-girls-tutorial/es-ES#

**Comment by ivigilm** [comment]
I'll try and do it this weekend. I still need to learn how to work with Crowdin.

**Comment by magul** [comment]
Great, thanks!

**Comment by ivigilm** [comment]
Hello again. I can't seem to be able to integrate changes from Github into Crowdin. Maybe I don't have permission?

**Comment by magul** [comment]
What does it mean @ivigilm ? I see that you successfully joined the project (as a translator).

Are you not able to propose a translation on Crowdin? Is it connected with voting for translations feature on Crowdin? Can you, please, create an issue for such problem on Crowdin (see screenshot on how to do so).

Screenshot from 2019-10-14 09-49-13

**Comment by ivigilm** [comment]
Ok. I thought I could just import the whole project from GitHub. Maybe I'm missing something but it seems as if I could only translate a document once sentence at a time. Is this right?
I was confused because there's a Github Integration tool on Crowdin (https://support.crowdin.com/github-integration/), but it seems to be only available to project managers. Can you do that or is translating everything again the only option?

**Comment by magul** [comment]
We do use the Github Integration tool on Crowdin. We fetch source language from Github (that means English) and we Crowdin push all translations to one dedicated branch (which we don't use, as we took a more granular approach, to introduce changes by destination language).

Unfortunately, I don't know if that's possible to apply a batch of changes from Github to Crowdin onto destination/target language (in this example Spanish).

**Pull request merged**
