### PR TITLE
Fixed volunteers list in pt translation

### PR DESCRIPTION
**Pull request by marcelometal**

### CODE REVIEW

**Comment by ayr-ton** [comment]
Also fixed on #1050

**Comment by marcelometal** [comment]
Hi @ayr-ton, I believe that small commits are widely considered to be best practice. Your commit in #1050 is a mixed of many fixes. For example, If a feature needs to be rolled back, you can rollback one changeset not "half" of a changeset. So, IMHO you should remove "volunteers list" changes from your commit in favor of this PR.

**Comment by ayr-ton** [comment]
@marcelometal Fair enough. I have removed that changes on #1050, as suggested. :-)

**Comment by ayr-ton** [comment]
+1

**Comment by ayr-ton** [comment]
Any reviewer has any thoughts on this one? 💃

**Comment by aniav** [comment]
No thoughts, just merges! 🎉

**Pull request merged**
