### PR TITLE
[fr] [django_models] Fixed incorrect file name.

### PR DESCRIPTION
**Pull request by AdrianGaudebert**
@olasitarska r?

### CODE REVIEW

**Comment by AdrianGaudebert** [comment]
Actually, I'm going to add more typo fixes to this pull request as the day goes on. Don't merge yet, please. :)

**Comment by olasitarska** [comment]
Ok, let us know when it's ready to merge :)

**Comment by AdrianGaudebert** [comment]
Well the workshop is over and I heard no other complaints about the tutorial. I suppose it's "ready". :)

**Comment by aniav** [comment]
:sparkles: :cat:

**Pull request merged**
