### PR TITLE
Turkish Translation

### PR DESCRIPTION
**Pull request by kyzn**
Congratulations and thanks to all volunteers who helped translate & proofread DjangoGirls Tutorial into Turkish!

### CODE REVIEW

**Comment by tricoder42** [comment]
Wow, that's super awesome! I'll review it today so we can publish it soon! Thank you for great work :+1:

**Comment by uskudarli** [comment]
Excellent. You guys were all on fire. Would love to have it available for our mentors meeting on Satuday, if possible. 

This community and the extended community are simply great.

**Comment by muratkun** [comment]
WP team, well done everyone. 

So excited about December 12.th First Djangogirls in Turkey- İstanbul. 

Yey!

**Comment by tricoder42** [comment]
Build is green, translation is online: http://tutorial.djangogirls.org/tr/index.html

Thank you everyone for your help :tada: :confetti_ball: :+1: :rocket: :guitar:

**Comment by uskudarli** [comment]
Thrilled!

**Pull request merged**
