### PR TITLE
Japanese translation improvements from Crowdin made by:

### PR DESCRIPTION
**Pull request by magul**
* capricorni (https://crowdin.com/profile/capricorni)
* Doarakko (https://crowdin.com/profile/Doarakko)
* Doppo (https://crowdin.com/profile/Doppon)
* ebiiim (https://crowdin.com/profile/ebiiim)
* ftnext (https://crowdin.com/profile/ftnext)
* Kazuki Imamura (https://crowdin.com/profile/kaizumaki)
* kocozt (https://crowdin.com/profile/kocozt)
* mamix1116 (https://crowdin.com/profile/mamix1116)
* mizzsugar (https://crowdin.com/profile/mizzsugar)
* rikuru (https://crowdin.com/profile/r1kuru)
* ryouichirou_nagami (https://crowdin.com/profile/ryouichirou_nagami)
* Saba Motto (https://crowdin.com/profile/sabamotto)
* Seiichi Ariga (https://crowdin.com/profile/seiichi.ariga)
* takaakifuruse (https://crowdin.com/profile/takaakifuruse)
* yosu (https://crowdin.com/profile/woodstock830)
* YUKI (https://crowdin.com/profile/YukieK)

### CODE REVIEW

**Comment by magul** [comment]
There's no activity from @DjangoGirls/ja-pr for more than a week. Merging without explicit approval.

**Comment by ftnext** [comment]
@magul
Thank you for merging translation improvement.

I am engaged in review of Japanese translation in Crowdin, and 83% was reviewed on 1st October.

Could you merge translation improvement on 3rd October or 4th?
On 5th October, [a meeting for workshop coaches](https://djangogirls-org.connpass.com/event/140290/) will be held in Tokyo, and I want coaches to check the newest translation in the meeting.

**Comment by magul** [comment]
@ftnext sure thing, Give me just info when and I should prepare a pull request in less than an hour.

**Comment by ftnext** [comment]
@magul Thanks!
I want you to create a pull request and merge it between 13:00 4th Oct. (JST) and 24:00 4th Oct. (JST) when you like.
It seems to be between 6:00 and 17:00 in Poland.

**Comment by magul** [comment]
I should be available from 9 am CEST, but should prepare pull request in few hours.

**Comment by ftnext** [comment]
@magul 
Hi. I completed review of Japanese translation.
It is very helpful for you to create Pull Request (see Issue https://github.com/DjangoGirls/tutorial/issues/1615 )

**Pull request merged**
