### PR TITLE
Japanese translation improvements from Crowdin made by:

### PR DESCRIPTION
**Pull request by magul**
* ftnext (https://crowdin.com/profile/ftnext)
* Kazuki Imamura (https://crowdin.com/profile/kaizumaki)
* mizzsugar (https://crowdin.com/profile/mizzsugar)
* yosu (https://crowdin.com/profile/woodstock830)

### CODE REVIEW

**Comment by ftnext** [comment]
@magul Thank you for updating master branch!😃
I have a question: when the latest translation is **deployed**?

I was checking https://tutorial.djangogirls.org/ja/ for a few days,
but it seems the older version (not the latest) 🤔

A workshop in Tokyo will be held in next weekend (16th Nov.),
so I am glad if the latest Japanese translation is deployed by the Tokyo workshop.

**Comment by magul** [comment]
@ftnext, unfortunately, there's an internal problem with triggering GitBook content refresh from GitHub. We have in-depth conversation about that in #1613.

I'm in the middle of gaining access to GitBook (ping @GirlGeekUpNorth) but will also try to figure out if I'm able to trigger that deployment without using GitHub altogether.

Sorry for the inconvenience!

**Comment by magul** [comment]
No lucky there
```
magul@bohr tutorial (master=) $ git push gitbook master
Username for 'https://git.gitbook.com': magul
Password for 'https://magul@git.gitbook.com': 
Enumerating objects: 222, done.
Counting objects: 100% (167/167), done.
Delta compression using up to 4 threads
Compressing objects: 100% (85/85), done.
Writing objects: 100% (106/106), 83.77 KiB | 5.24 MiB/s, done.
Total 106 (delta 41), reused 40 (delta 11)
remote: error: failed to lock refs/heads/master
To https://git.gitbook.com/djangogirls/djangogirls-tutorial.git
 ! [remote rejected]     master -> master (failed to lock)
error: failed to push some refs to 'https://git.gitbook.com/djangogirls/djangogirls-tutorial.git'
```

**Comment by magul** [comment]
It occurs that even if CLI states update was rejected it occurs on a website. Can you confirm, that there's a most up-to-date version of Japanese tutorial?

**Comment by ftnext** [comment]
>Can you confirm, that there's a most up-to-date version of Japanese tutorial?

I think that Japanese translation in this repo is the most up-to-date,
and Japanese translation in https://tutorial.djangogirls.org/ja/ is older than this repo.
It seems that there are the above 2 versions to me.

- current version of Japanese translation (https://tutorial.djangogirls.org/ja/ ) : https://github.com/DjangoGirls/tutorial/commit/9c18ee3987dd87a1209764f08104065e6e716a93 (merged #1574 )
- latest version of Japanese translation: https://github.com/DjangoGirls/tutorial/commit/0b5c4c084ab77dfba716a877611d0cb44f87d094 (merged #1616 )

**Comment by magul** [comment]
@ftnext after I asked you to check I did also some checks by myself and I can confirm that this commit 

https://github.com/DjangoGirls/tutorial/commit/0b5c4c084ab77dfba716a877611d0cb44f87d094 is available on GitBook right now (at least the anchors for subchapters of `Installation` chapter are these that were introduced in this commit).

On what basis you're claiming that there's different commit?

**Comment by ftnext** [comment]
@magul The issue seems to have been resolved in the last half day.
I checked 0b5c4c0 is available on GitBook at the following points:

- the table of contents in left side
    - half day before: Django URLs (at https://github.com/DjangoGirls/tutorial/commit/9c18ee3987dd87a1209764f08104065e6e716a93 )
    - -> now: Django URL
- [What's next](https://tutorial.djangogirls.org/ja/whats_next/)
    - half day before: Dajngo (there was a typo at https://github.com/DjangoGirls/tutorial/commit/9c18ee3987dd87a1209764f08104065e6e716a93 )
    - -> now: Django (the typo is fixed by available translation of 0b5c4c0 )

> On what basis you're claiming that there's different commit?

The basis is as above.

[My question](https://github.com/DjangoGirls/tutorial/pull/1616#issuecomment-552053241) is resolved now and I am relieved that the latest Japanese translation is available.
It is strange that Japanese translation is updated after some days from merge.
Thank you for your effort!

**Comment by magul** [comment]
Unfortunately, there are issues with GitHub -> Legacy Gitbook integration. I manually refreshed the content of the tutorial yesterday. More info about how I achieved that you can find in #1613 but info about that should be also in few comments above.

**Pull request merged**
