### PR TITLE
Remove need for whitenoise and collectstatic

### PR DESCRIPTION
**Pull request by glenjamin**
Enabling the same WSGI middleware that is used by runserver allows us to simplify the static files process, and remove a bunch of steps.

As discussed in #641

### CODE REVIEW

**Comment by olasitarska** [comment]
@glenjamin This looks good! Have you had a chance to actually test it with the rest of the Django Girls blog? Just making sure this approach actually works as described at PythonAnywhere, etc :)

**Comment by glenjamin** [comment]
Yup, it's running on https://github.com/glenjamin/djangogirls-tutorial

If someone else is able to verify then that would be good too!

**Comment by phalt** [comment]
@olasitarska ran through this with @glenjamin at DjangoGirls Sheffield to verify. Looks grand! :+1:

**Comment by olasitarska** [comment]
Awesome! Thanks everyone :)

**Pull request merged**
