### PR TITLE
alter model, migrate, add external dependency

### PR DESCRIPTION
**Pull request by mfrasca**
I've added an extra page after the `Forms` page.  the goal is to show the usage of `select2` widgets, and along the way, to expose the reader to a few more concepts.  I plan to expand the page with a section on ModelSelect2Widget, but let's first see what you folks think of it.  I hope this can be twisted into fitting in the project, I think it's a valuable addition, I'm sure it can be expanded, for example it misses the 'deploy' section, and I'm not a very graphical person so I guess you want to add screenshots or something.

### CODE REVIEW

**Comment by das-g** [comment]
There's lots of interesting aspects that could be added to the tutorial. But it already is long enough (if not already a bit too long) as it is. Don't forget that it is used for workshops, most of which aren't longer than one single day.

Thus, I'm against adding more topics to the tutorial unless they're absolutely essential for giving the participants a glimpse onto programming and software development by making a simple blog. Note that even [making the application somewhat secure](https://tutorial-extensions.djangogirls.org/en/authentication_authorization/) is covered only in an "extension" of the tutorial rather than the main Django Girls tutorial itself. And even that doesn't handle important topics like how (and why) to avoid checking in (and thus publishing)  the Django `SECRET_KEY`.

Therefore, I'd suggest you consider to contribute this addition as a new chapter of the Django Girls tutorial extensions (https://github.com/DjangoGirls/tutorial-extensions) instead of the main tutorial. (If there's a reason why this absolutely must be covered in the main tutorial, please let us know.)

**Comment by mfrasca** [comment]
hi @das-g , thank your reviewing.  and no, there isn't any **absolutely** reason anywhere.  I do think that the `migration`, `patch`, `external dependencies` are all worth mentioning, but as you say, they can likely go into a tutorial extension.  and yes, it's enough material for an extra couple of hours, if you want to assimilate it properly.  I was writing this in the process of understanding why django-select2 wasn't working for me, and I thought that my efforts were worth sharing.  

I can move this into 'tutorial extensions', without closing the pull request, I guess.

as announced, I plan adding a section on foreign key links, so what do you suggest in practice?  do you think you have someone who could help integrate the text / review / produce screenshots?  also, it would be nice to have someone making the text more reader-friendly, like the rest of your documentation.

if you don't close the pull request, I'll work further on it, I can't promise a deadline.

**Comment by mfrasca** [comment]
oh, but https://github.com/DjangoGirls/tutorial-extensions, that's a different repository, so let me know, what shall I do.  cheers, M

**Comment by das-g** [comment]
> oh, but https://github.com/DjangoGirls/tutorial-extensions, that's a different repository, so let me know, what shall I do, or if you want to suggest a title to what I've been writing. cheers, M

I'd suggest to open a new pull request there. (And to close this one.) As long as you don't consider the new chapter ready for publication, you can have it in a ["draft pull request"](https://help.github.com/articles/about-pull-requests/#draft-pull-requests) instead, so that it can already be reviewed but not yet merged. (Once you consider it ready, you can turn the draft pull request into a normal pull request.)

All work on the tutorial and on the tutorial extensions is done by volunteers. So if you want or need collaborators to get the new chapter ready, you yourself will probably have to convince them to work on that. I saw [you've already posted](https://gitter.im/DjangoGirls/tutorial?at=5ccc5b4b990feb451847312d)) on Gitter. Other online places to ask might be https://djangogirls.slack.com/ (although I'm unsure who can invite you there) and the issue trackers of the respective DjangoGirls repositories on GitHub.

**Comment by mfrasca** [comment]
have forked https://github.com/mfrasca/tutorial-extensions, and it's nice that we have a 'draft' status for pull requests.  it buys one visibility, without standing in the way of proper work.

**Pull request closed without merging**
