### PR TITLE
Small typo

### PR DESCRIPTION
**Pull request by FelipeSBarros**
Changes in this pull request:
Just fix a small typo en PT-BR;

### CODE REVIEW

**Comment by magul** [comment]
Hi!

Thank you for this contribution.

Can you, please, apply this change to our Crowdin project (as we tend to import up-to-date translations from there)? It's available under https://crowdin.com/project/django-girls-tutorial/pt-BR#

Thanks in advance!

**Comment by FelipeSBarros** [comment]
@magul , no problem. Un furtunatly I am not in crowin. I will chack if someone from the team could update this point.

**Comment by magul** [comment]
You can easily login there using your Github account. Also, Brazilian Portuguese is right now at 96% and it would be great to bump that up yet again to 100% (of course if you have time to do so).

Thanks!

**Comment by FelipeSBarros** [comment]
Done. Thx

**Pull request closed without merging**
