### PR TITLE
Adding a error handling solution in Forms spanish section

### PR DESCRIPTION
**Pull request by pamelipluas**
We found an issue with that could prove detrimental to the progress of our event. We've found a fix and are pushing it in case it pops up for someone else.

### CODE REVIEW

**Comment by ekohl** [comment]
My Spanish isn't very good, but does this fix https://github.com/DjangoGirls/tutorial/issues/1099?

**Comment by pamelipluas** [comment]
Yes, @ekohl, that is the fix for that issue.

**Comment by jheredia** [comment]
Thanks for the fix! @pamelipluas

**Comment by pamelipluas** [comment]
@ekohl @jheredia Welcome. Is it possible to get this PR merged?

**Comment by ekohl** [comment]
@pamelipluas I'm just a contributor like you. One of the maintainers should take a look.

**Comment by pamelipluas** [comment]
@helenst Is it possible to get this PR merged?

**Comment by lipemorais** [comment]
Looks good to merge for me. 👍

**Comment by aniav** [comment]
🎉

**Pull request merged**
