### PR TITLE
[Django 3.1] upgrade Python to 3.8

### PR DESCRIPTION
**Pull request by das-g**
Django 3.1 requires the newer Python version(s), so merge the Python version changes from #1683 also into branch `django-3.1`.

### CODE REVIEW

**Comment by nikhiljohn10** [comment]
@das-g Should I resolve the conflict in my branch and push?

**Comment by das-g** [comment]
> @das-g Should I resolve the conflict in my branch and push?

That'd be great, @nikhiljohn10! If not, I'll do it when I get to it.

**Comment by nikhiljohn10** [comment]
@das-g we need to fix https://github.com/DjangoGirls/tutorial/issues/1694 urgently before resolving this conflict i think.

**Comment by ramonsaraiva** [comment]
Should we take the opportunity to just upgrade Python to 3.9.x?

**Comment by das-g** [comment]
> Should we take the opportunity to just upgrade Python to 3.9.x?

That we can do independently of the switch to Django 3.1. Feel free to file a Pull Request towards the `master` branch.

**Comment by nikhiljohn10** [comment]
@das-g Once we merge #1731, I'll push the Python 3.9.5 PR for avoiding conflicts.

**Pull request closed without merging**
