### PR TITLE
Link not working

### PR DESCRIPTION
**Pull request by mauricioabreu**
Added 'en' as default redirect.

### CODE REVIEW

**Comment by bmispelon** [comment]
Hi,

I don't think we need to add a default language.
The current link uses `./` at the beginning which makes it relative and so it should work in all languages.

Thanks! :dash:

**Comment by mauricioabreu** [comment]
Ok, but the link still does not work. 
1 - Go to https://github.com/DjangoGirls/tutorial
2 - Try to click the link
3 - Page not found

:-)

**Comment by bmispelon** [comment]
Oh, I see. You're navigating directly from github.

Our tutorial is meant to be viewed from http://tutorial.djangogirls.org.
I don't know if there's a way to support both github and our normal tutorial (which is translated in 3 languages).

**Comment by mauricioabreu** [comment]
Yep! It is ok! 
I did not know you were moving. Last time I checked this repo it had no translation to other languages.

Thanks for reviewing my patch though! :-)

**Pull request closed without merging**
