### PR TITLE
Fix typo in the Brazilian Portuguese language

### PR DESCRIPTION
**Pull request by gabrielheming**
Fixed a few typos in the Brazilian Portuguese language.

### CODE REVIEW

**Comment by magul** [comment]
Hello there! Can You also apply your changes on Crowdin? We're trying to manage translation there.

Portugese version is here (that was not yet merged here, `pt` directory here contains Brazilian Portugese): https://crowdin.com/project/django-girls-tutorial/pt-PT#

Brazilian Portugese version: https://crowdin.com/project/django-girls-tutorial/pt-BR#

**Comment by gabrielheming** [comment]
Hi magul. I did that, there isn't typo on there (that I've seen so far). I'll take another look though.

But I have a quetion. For new translation (that I did there), I have to open a new pull request or just wait for the approve?

**Comment by gabrielheming** [comment]
Yes, I've been doing the translation (Brazilian Portuguese) on Crowdin right now.

**Comment by magul** [comment]
Great! :+1:

**Comment by aniav** [comment]
I'll close this one as the changes from this PR have been introduced on Crowdin and they have also been released last month. Sorry you had to wait so long! 💃

**Pull request closed without merging**
