### PR TITLE
'python3' doesn't work on Windows

### PR DESCRIPTION
**Pull request by eppyk**
'python3' command doesn't work on Windows :( must be 'python'.

### CODE REVIEW

**Comment by aniav** [comment]
I am sure we have changed it there and back from `python` to `python3` and so on more than once already. I feel this should be throughly investigated and we should find the situations where you have `python` and not `python3` commands on Windows. Could someone give some more feedback?

**Comment by eppyk** [comment]
I'm not qualified enough to investigate this, but I hope someone knows what the problem might be! :) Thanks for your reply Ania.

**Comment by eppyk** [comment]
I suspected it's because on MacOS you already have Python2 installed, so you kind of have to differ between Python2 (being the default) and Python3 and that's why you need the command to be python3. Maybe it depends on whether you have another version of python already installed on your computer?
I don't really know, just guessing.

**Comment by aniav** [comment]
I can't merge it automatically, but adding your changes by hand in a second! :heart: :sparkles:

**Pull request closed without merging**
