### PR TITLE
UA: fix grammar

### PR DESCRIPTION
**Pull request by MaxymVlasov**

### CODE REVIEW

**Comment by MaxymVlasov** [comment]
@alexanderad, I done
Check, please

**Comment by alexanderad** [comment]
@patjouk I went through the changes and confirm this one is good to :ship:

**Comment by alexanderad** [comment]
@MaxymVlasov you might also want to squash all commits into one before it will be merged.

**Comment by MaxymVlasov** [comment]
@alexanderad Good idea. I did it.

**Comment by webknjaz** [comment]
@alexanderad actually GitHub has introduced squashing merge commits a while ago, so one doesn't need to do this locally (just check the pull-down menu in Merge button)

**Comment by aniav** [comment]
Thank you! 👍

**Pull request merged**
