### PR TITLE
Integrated the tabs plugin

### PR DESCRIPTION
**Pull request by woeye**
Also updated en/python_installation/instructions.md in to show how to use the plugin.

Changes in this pull request:

-
-
-

### CODE REVIEW

**Comment by aniav** [comment]
This is great! I can't merge it for now, because we need to change all the files at once to have the simpletabs instead of collapsible panels, so we will not confuse the users :)

**Comment by ekohl** [comment]
Could we revisit this and integrate it on every page?

**Comment by aniav** [comment]
I think I need to close this. We are now running gitbook on the legacy version of the platform and the new version of gitbook is incompatible with plugins, so effectively in order to upgrade to new version of gitbook we would need to remove the code related to this.

Sorry it never got merged 😢

**Comment by das-g** [comment]
> I think I need to close this. We are now running gitbook on the legacy version of the platform and the new version of gitbook is incompatible with plugins, so effectively in order to upgrade to new version of gitbook we would need to remove the code related to this.

Well, we are already using a plugin, albeit a different one. Are there any plans to switch to the new GitBook version in the foreseeable future?

**Comment by aniav** [comment]
We are using the other plugin, but merging this PR would require additional work in the whole repository, so the plugin is updated in all places. Quite a big refactor itself.

As for plans to switch to a new version, I don't think there are any before someone decides to actually implement it 🤷‍♀

**Comment by magul** [comment]
@das-g @aniav two things here:

 * That plugin can potentially solve the problem with Crowdin inability to properly render  sections using `<!--sec` syntax (see: https://github.com/DjangoGirls/tutorial/pull/1539#issuecomment-515680553 and #1541)
 * We have at least to issues, that try to describe how we're publishing newest tutorial versions: #1271 and #902. My understanding is that deliverable of #1271 should be a description available in  https://github.com/DjangoGirls/translation-guide that will probably increase translators engagement in the flow that we tend to use. The second one (#902) is for me a little too broad in scope. We should split it in my opinion into 3 separate issues: GitBook, Crowdin and Markdown. If we want to migrate from legacy to GitBook (or any other solution) I believe that need to be carefully planned to minimalize the impact in what we already have in translations.

**Pull request closed without merging**
