### PR TITLE
Typo correction in Korean "Deploy!" chapter: "삭제되도" → "삭제돼도"

### PR DESCRIPTION
**Pull request by ssep4u**
오타 수정
삭제되도 -> 삭제돼도

Changes in this pull request:

-
-
-

### CODE REVIEW

**Comment by das-g** [comment]
> 오타 수정
> 삭제되도 -> 삭제돼도

(google-translate-aided) Translation:
> Typo correction
> "삭제되도" &rarr; "삭제돼도"

**Comment by das-g** [comment]
Please also suggest this fix [on Crowdin](https://crowdin.com/translate/django-girls-tutorial/296/en-ko).

**Comment by aniav** [comment]
The Korean version on crowdin is now completely different but this changed (google translated) seems like a good improvement. Merging 👍

**Comment by das-g** [comment]
Are there any plans on how to get our Korean content on Crowdin back in sync?

**Comment by aniav** [comment]
So I guess the translation there is just more up to date as far as I checked. Means the next time it's ready we can update the whole translation 😊

**Pull request merged**
