### PR TITLE
[Russian] fixed - (Changes to copy)

### PR DESCRIPTION
**Pull request by mounlion**

### CODE REVIEW

**Comment by aniav** [comment]
Thank you! 💪

**Comment by b0g3r** [comment]
How is it customary to refer in the text to attendee: how to a woman, or how to a man?
This pull request changed the reference to the male

**Comment by aniav** [comment]
We would like female ones...

**Comment by lancelote** [comment]
@aniav I think this PR should be reverted, it changed correct female-endings to male ones.

**Comment by aniav** [comment]
Ok, reverting it then! Thank you :)

**Pull request merged**
