### PR TITLE
Making post_detail.html more consistent

### PR DESCRIPTION
**Pull request by veuu**
so that it matches Chapter "Extend Your Application"

More progress from #241

### CODE REVIEW

**Comment by kvbik** [comment]
i like this PR very much :)

**Comment by olasitarska** [comment]
Nice, děkuji! :) :tada: :penguin: :heart_eyes_cat:

**Comment by Natrossyandexru** [comment]
Hello,
I am following the tutorial now, but I am not able to access http://127.0.0.1:8000/ when I tried to deploy. I would appreciate it if you could give any advice.

**Comment by magul** [comment]
@Natrossyandexru there's a much bigger change to get support using our Gitter channel available here: https://gitter.im/DjangoGirls/tutorial

**Pull request merged**
