### PR TITLE
Change Python 3.6 to 3.5

### PR DESCRIPTION
**Pull request by maxtortime**
I think `pythonanywhere` doesn't provide **3.6** version, but in this tutorial use **3.6**, So I change them to python **3.5**.

image

Changes in this pull request:

- Change all 3.6 text to 3.5 text.

### CODE REVIEW

**Comment by magul** [comment]
It actually support Python 3.6. Did you make this screenshot today or it originate from current tutorial chapter?

**Comment by magul** [comment]
I forgot about link https://blog.pythonanywhere.com/151/

**Comment by maxtortime** [comment]
I captured above screenshot yesterday. 

image

But it is also same situation today. How can I use Python 3.6 for bash console?

**Comment by das-g** [comment]
@hjwp Do the available Python version differ between PythonAnywhere accounts?

**Comment by maxtortime** [comment]
@das-g I think so too. I guess this is the difference between the paid version and the free version.

**Comment by hjwp** [comment]
if you have a really old pythonanywhere account it may still be on the old system image, which does not have python 3.6.  you can ask for it to be upgraded to the new image at any time by emailing support@pythonanywhere.com.  it's free.

**Comment by hjwp** [comment]
actually the very latest system image even has python3.7 as well as 3.6!  https://blog.pythonanywhere.com/166/

**Comment by maxtortime** [comment]
Thanks. I think it is a problem that is limited to me.

**Pull request closed without merging**
