### PR TITLE
Fix some French formatting

### PR DESCRIPTION
**Pull request by kh3phr3n**
Just few corrections in style, grammar and conjugation.

### CODE REVIEW

**Comment by olasitarska** [comment]
So this is a problem, and I don't really know what to do with this. We're handling all translations via Crowdin, and I'm afraid that if I'm going to merge this pull request, it's gonna be conflicted with recent changed in Crowdin. 

What should we do? @aniav @tricoder42 @rapoulson

**Comment by tricoder42** [comment]
Yes, translations should be definitely updated in Crowdin :( I know it's a lot of text (thank you for that :sun_with_face: ), but it should take few minutes of copy-pasting...

There is a way how to upload new translations from codebase to crowding, but I'm not sure how smart it is. I would be afraid that it overwrite any changes made in Crowdin since last build :/

Maybe we should highlight in README that *all* translations must be done in Crowdin...

**Comment by kh3phr3n** [comment]
Ok no problems, don't worry, maybe a next time :blush:

**Comment by rapoulson** [comment]
:+1: To updating the README. I get so bummed when I see people work really hard and it's a duplicate of work in Crowdin :disappointed: @kh3phr3n the new French version we're working on in Crowdin is getting really close to done! If you'd like to contribute over there or help proofread, please let us know and we'll be happy to set you up with access!

**Pull request closed without merging**
