### PR TITLE
removed <blockname> #986

### PR DESCRIPTION
**Pull request by tugce**

### CODE REVIEW

**Comment by ekohl** [comment]
I don't think this is the correct implementation for https://github.com/DjangoGirls/tutorial/issues/986. You are now removing it from the opening block too but I think that should stay. So ```{% block content %}``` is still needed but ```{% endblock content %}``` can be ```{% endblock %}```.

**Comment by ekohl** [comment]
There are still some unrelated changes that look like a too global search-and-replace. Could you have a look at those as well?

**Comment by aniav** [comment]
This definitelly neeeds fixes as now it would break the build of gitbook :)

**Comment by aniav** [comment]
I have resolved #986 in another commit as this PR is too broad and hanging for a long time. I am closing that now. Thank you! 👍

**Pull request closed without merging**
