### PR TITLE
Put 박제권's (Jay Park's) name in Korean.

### PR DESCRIPTION
**Pull request by jinto**
My english name is Jay Park and korean name is 박제권. You can confirm it on the linked page( https://jinto.pe.kr) after the name .

Changes in this pull request:

- Name of a translater.

### CODE REVIEW

**Comment by jinto** [comment]
I've changed PR title cause it looks not polite. It was just commit message and it goes to title of the pr, sorry for my mistake. and thanks for reviewing in advance.

**Comment by das-g** [comment]
> I've changed PR title cause it looks not polite. It was just commit message and it goes to title of the pr, sorry for my mistake. and thanks for reviewing in advance.

Thank you. The original PR title would actually have been OK, but the new one is fine, too. :smile:

Do you still have your Crowdin account? If so, could you write me a message within crowdin to verify that you're indeed the same person?

**Comment by magul** [comment]
I don't believe that translation origins in Crowdin @das-g

**Comment by das-g** [comment]
> I don't believe that translation origins in Crowdin @das-g

@magul At least there indeed is a "Jay Park" in our list of translators since over 5 years ago:
Bildschirmfoto von 2020-12-01 17-31-09

**Review by das-g — APPROVED** [review]
Crowdin user [jaypark](https://crowdin.com/profile/jaypark) confirmed to me via Crowdin message that he is indeed the author of this PR.

@magul shall we merge or does this need confirmation from @DjangoGirls/ko-pr first?

**Comment by magul** [comment]
By default whenever somebody changes something in particular language I'm asking that language reviewers to review, but I don't believe we have a strict policy in place here.

That looks really like minor change and if your're confident that's right, I would say: go for it!

**Comment by magul** [comment]
two side notes here:
 * we can also add @jinto as a member of Koeran reviewers team here on Github
 * I believe I received an email, that Korean translation on Crowdin was completed, so there will be a pull request (which will be huge)

**Pull request merged**
