### PR TITLE
specify on_delete=CASCADE in models.py for Django 2.0 compatibility

### PR DESCRIPTION
**Pull request by cf0af844a67a12276984d45b5fa92cbd**

### CODE REVIEW

**Comment by hjwp** [comment]
Hi there, the current code for models.py seems to work OK for me, any insight on why we need this?

 in #1212 @anezkamll mentions it caused an error on PythonAnywhere, is there any more info on what that was?

**Comment by magul** [comment]
@hjwp at this moment tutorial (at least English version) supports Django 1.11 and this change is required by Django 2.x (and because it's out there lot of people try to use it and get an error here).

**Comment by ekohl** [comment]
And 1.11 shows a deprecation warning IIRC so it's a good preparation.

**Comment by hjwp** [comment]
understood!  thanks y'all.

**Comment by ekohl** [comment]
Thanks!

**Comment by ekohl** [comment]
https://github.com/DjangoGirls/tutorial/pull/1219 makes it consistent for all other languages.

**Pull request merged**
