### PR TITLE
Reminder for opening files in code editor

### PR DESCRIPTION
**Pull request by bauerv**
Participants got confused, expecting to open the source files and editor from the shell. I suggest adding a note to remind them that they can open the files as they are used to from other programs

### CODE REVIEW

**Comment by patjouk** [comment]
Hi @bauerv. Can you modify this PR so it only contains changes in files `en/django_start_project/README.md` and `en/django_models/README.md`? Thanks :)

**Comment by bauerv** [comment]
I would love to and was trying to, but couldn’t figure out how to do it :S Any suggestions how to fix this? Thanks!

**Comment by patjouk** [comment]
You can use branches to submit different PR. You can find more info here: https://github.com/Kunena/Kunena-Forum/wiki/Create-a-new-branch-with-git-and-manage-branches
Tell me if you need help :)

**Comment by bauerv** [comment]
Ok, I created new branches for the changes and will create new PR for them. Closing this one now. Still not sure now, how to get my local fork in sync with the official tutorial though... Sorry for the complications, I'm only starting getting used to git..

**Comment by bauerv** [comment]
actually, I'm not getting there :( I somehow only keep adding commits to my local master and branches that then I can not remove from pull requests to the official tutorial. I tried a rebase on my machine to get rid of the redundant commits, but now it's only worse. Currently I only see the option of deleting my fork and starting over. Maybe you could have a look at the other PRs that I have and merge them if they are useful before I shut down my fork?

**Pull request closed without merging**
