### PR TITLE
specify PythonAnywhere console

### PR DESCRIPTION
**Pull request by nusnivek**
specify PythonAnywhere console

### CODE REVIEW

**Comment by das-g** [comment]
Due to including the commit 239db53 which reverts the changes from ecababf and 4db0629, this PR doesn't change anything (except adding that for-and-back-change history). Is that intended?

**Comment by nusnivek** [comment]
Sorry, new to GitHub. That is not intended.

**Comment by das-g** [comment]
Do one of the following
- create a [new pull request for your existing branch `nusnivek-patch-1`](https://github.com/nusnivek/tutorial/pull/new/nusnivek-patch-1)
  _or_
- reopen pull request #1426 and edit its title to better describe the actual change

**Comment by nusnivek** [comment]
Sorry again --- I trial-and-error'ed some stuff before seeing your comment. I hope everything's clear now with #1427

**Pull request closed without merging**
