### PR TITLE
Django official link

### PR DESCRIPTION
**Pull request by tfevan**
edited django official link  with new **django  1.11** version

### CODE REVIEW

**Comment by aniav** [comment]
I think we can't update the link to Django 1.11 in languages which use Django 1.8. If I remember there might have been bigger changes between these versions? Have you checked that?

**Comment by ekohl** [comment]
Even English still explicitly installs 1.10 so IMHO it should really point to the version which ```pip install``` will give.

**Comment by aniav** [comment]
Different languages are translated to different versions of Django because the instructions between versions change a bit and we also change the english version upon pull requests and/or issues on the repo.

The tutorial gives directions on installing Django with a specific version number, currently this is `pip install django~=1.10.0` so if we are changing the version number in the tutorial we need to
a) update all instructions for the specific language
b) check if the instructions shouldn't be changed in terms of deprecation warnings and functional changes in Django itself.

**Comment by ekohl** [comment]
@aniav said what I meant :)

**Pull request closed without merging**
