### PR TITLE
gitignore - ignore .vscode dir

### PR DESCRIPTION
**Pull request by ondrejsika**
Changes in this pull request:

- Add .vscode to gitignores in all languages mutations

### CODE REVIEW

**Comment by magul** [comment]
@das-g that change will be also propagated by Crowdin so will not care much about languages that will be affected here (of course beside English one).

**Comment by das-g** [comment]
> @das-g that change will be also propagated by Crowdin so will not care much about languages that will be affected here (of course beside English one).

I know, but the PR description claims this PR makes this change
> [...] in all languages mutations

I think that for clarity either should be done completely, or only the English version should be changed and all other languages changed through Crowdin. Off course we could also work with a mixed approach, so if you want, feel free to merge this PR as-is.

**Comment by ondrejsika** [comment]
I'll update content & description of PR.

Thanks,
O.


--
Ondrej Sika
ondrej@ondrejsika.com (primary, personal)
ondrej@sika.io (freelance)
+420 773 452 376
https://t.me/ondrejsika (Telegram)

**Comment by das-g** [comment]
Hey @ondrejsika. Do you plan to continue work on this PR?

**Comment by kaizumaki** [comment]
@das-g @ondrejsika  If no one wants to continue this PR, can I do it?

**Pull request closed without merging**
