### PR TITLE
Japanese translation from Crowdin (fixes #1170)

### LINKED ISSUE #1170: Japanese Translation of the tutorial
The Japanese translation of the tutorial is available here-
 https://djangogirlsjapan.gitbooks.io/workshop_tutorialjp/

Should we ask the tutorial translator to add the translated tutorial here?

### PR DESCRIPTION
**Pull request by magul**
Beta version as it was not yet proofread.

Translation made by:
 * Anna Warzecha (vi) (https://crowdin.com/profile/aniav)
 * Ayako Matsumoto (https://crowdin.com/profile/sandream)
 * ftnext (https://crowdin.com/profile/ftnext)
 * ged1959 (https://crowdin.com/profile/ged1959)
 * Hiroshi Omata (https://crowdin.com/profile/homata)
 * kaizumaki (https://crowdin.com/profile/kaizumaki)
 * Kentaro0919 (https://crowdin.com/profile/kentaro0919)
 * kskkskksk (https://crowdin.com/profile/kskkskksk)
 * mamix1116 (https://crowdin.com/profile/mamix1116)
 * Saori Ota (https://crowdin.com/profile/saorio)
 * ssg (https://crowdin.com/profile/ssg)
 * Sourav Singh (https://crowdin.com/profile/souravsingh)
 * TAKAHASHI Shuuji (https://crowdin.com/profile/shuuji3)
 * WXMIN (https://crowdin.com/profile/WXMIN)
 * yosu (https://crowdin.com/profile/woodstock830)

Living book available here: https://magul.gitbooks.io/django-girls-tutorial/content/v/crowdin-translation-ja/

### CODE REVIEW

**Comment by magul** [comment]
@ftnext @mamix1116 @yosu @kaizumaki @maisuto @shuuji3 @ged1959 @souravsingh @wxmin @saorio @homata @kentaro0919 please review the whole translation (it's available here: https://magul.gitbooks.io/django-girls-tutorial/content/v/crowdin-translation-ja/)

There were some issues with `{% raw `%}` and `</code>` tags that were causing build fail. I tried to fix them on Crowdin (see last 3 commits or last 9 updates to Japanese language on Crowdin) but I'm almost sure, that there are more bugs that need to be spotted, before we will proceed with this pull request.

Thanks in advance!

(CC: @aniav @RachellCalhoun )

**Comment by souravsingh** [comment]
Looks good to me. Need a second pair of review from someone who is a native speaker of Japanese.

**Comment by mamix1116** [comment]
@magul @souravsingh Thank you so much for fixing tags and all your jobs.   I think I can check them out this weekend.

**Comment by magul** [comment]
Threre's some GitBook issue, that cause branch ref to not work - current version is available by commit hash here: https://magul.gitbooks.io/django-girls-tutorial/content/v/a1d5ba3c54372bf5938676791625ab59f65c727c_6/

I would wait for a week for review, but be aware that this one is a beta release (meaning that translation should be proofread on Crowdin), so unless there will be some major issues, I would go further with this branch.

**Comment by yosu** [comment]
Thank you for your great work!

I'll check the current version in this week.

**Comment by magul** [comment]
@souravsingh @mamix1116 @yosu I saw that somebody created @DjangoGirls/ja-pr team but I'm not able to add it to this particular PR as reviewer. I also saw that @yosu is working on Crowdin, so I just built your newest changes and push them here, they available in: https://github.com/DjangoGirls/tutorial/pull/1299/commits/31c349bd27b8d39e0b0321dd3b4b7392d1fc8501 and rendered version is available here: https://magul.gitbooks.io/django-girls-tutorial/content/v/31c349bd27b8d39e0b0321dd3b4b7392d1fc8501_2/

I also increased your privileges to Proofreaders, so You could mark translation there as proofread, one sentence at the time.

**Comment by yosu** [comment]
Thanks! I'll continue to proofread for a while.

**Comment by magul** [comment]
I just squashed @yosu todays changes to previous commit (just limit number of them).

Newest changes should be available here: https://magul.gitbooks.io/django-girls-tutorial/content/v/577f5583ce79760c91f4d773b13564738ca7e03a_1/

**Comment by magul** [comment]
Newest version available here: https://magul.gitbooks.io/django-girls-tutorial/content/v/2bcd9639b2d53611f54b1196041cf417b263fb6c/

**Comment by magul** [comment]
Newest build: https://magul.gitbooks.io/django-girls-tutorial/content/v/7447e7200c6e82be98f6f1b72eb378d0a538707d/

**Comment by magul** [comment]
https://magul.gitbooks.io/django-girls-tutorial/content/v/b6ca01cb5c7934b6fce39eb3bbc90d0358d1718b_1/

**Comment by magul** [comment]
Newest build: https://magul.gitbooks.io/django-girls-tutorial/content/v/18f1ee1b13a50117ddf5ef8f35de6e98c2696d27/

**Comment by magul** [comment]
@yosu I just merged update that introduces Django 2.0 - there will be around 5% drop in translation coverage. Just FYI.

**Comment by magul** [comment]
Newest build (intoducing Django 2): https://magul.gitbooks.io/django-girls-tutorial/content/v/4feefeb39fbf18307520ce19b93ecab44f81cd51/

**Comment by magul** [comment]
Newest build: https://magul.gitbooks.io/django-girls-tutorial/content/v/e5292a7a09440ecd511430fe40cfa6adcf79d60c_1/

**Comment by yosu** [comment]
@ftnext I appreciate your careful correction. I thought you were suitable for proofreaders, so I increased your privileges to Proofreaders.

**Comment by magul** [comment]
Newest build: https://magul.gitbooks.io/django-girls-tutorial/content/v/06aceac5d1e6e54b6aa6a85838030ea8153bc6c5/

**Comment by yosu** [comment]
I’ve finished the first review of whole translations.

I also approved the translations other than what I translated.

**Comment by magul** [comment]
Because there were some changes in English (source) version Japanese version coverage drop to 99% - could You update it to be up-to-date? Then I will build newest version here and we will merge it?

**Comment by yosu** [comment]
@magul Yes, I do.  I think it’s all right as a beta release.

**Comment by magul** [comment]
So I'm merging it!

**Comment by ftnext** [comment]
@magul 
Japanese translation review has reached 100%. (Proofread is over.)
Would you merge the latest translation to master branch?

@yosu 
Thank you for your effort! We have accomplished!!

**Pull request merged**
