### PR TITLE
Added Korean translation

### PR DESCRIPTION
**Pull request by sujinleeme**

### CODE REVIEW

**Comment by olasitarska** [comment]
@rapoulson or @tricoder42, would you have time to test it locally with Gitbook today? if no, I can probably get to it in the evening.

@sujinleeme, thanks for MASSIVE work :)

**Comment by rapoulson** [comment]
This is awesome @sujinleeme ! :confetti_ball: Thank you!

@olasitarska I'm happy to test it locally tonight! :smile:

**Comment by olasitarska** [comment]
@rapoulson gonna leave it up to you then! :)

**Comment by rapoulson** [comment]
Looks good to me! :tada:

**Pull request merged**
