### PR TITLE
Add about Visual Studio Code to Instructions in English and Japanese

### PR DESCRIPTION
**Pull request by ayatokura**
Changes in this pull request:

- Add about Visual Studio Code to Instructions in English
- Add about Visual Studio Code to Instructions in Japanese

Thanks.

### CODE REVIEW

**Comment by ayatokura** [comment]
Visual Studio Code is one of popular editor.
Thanks.

**Comment by ekohl** [comment]
We also have https://github.com/DjangoGirls/tutorial/pull/1296 and https://github.com/DjangoGirls/tutorial/pull/1315. It'd be nice if we could unify those all in a single PR.

**Comment by magul** [comment]
Also as we're trying to track changes between source language (English) and target language (in this example Japanese) it would be great it this pull request will be limited only to English and Japanese version will be introduced on our Crowdin project here: https://crowdin.com/project/django-girls-tutorial/ja#

**Comment by aniav** [comment]
I'll close this one as we've merged a PR introducing VSCode and Japanese change has to happen in Crowing either ways 👍

**Pull request closed without merging**
