### PR TITLE
Simple czech fixes

### PR DESCRIPTION
**Pull request by kvbik**
i hope i am not breaking the translation workflow by fixing the typos (and bit of grammar) here via github pull request - cc @tricoder42 

ps: thx everybody for all the hard work! authors of the text, translators, attendees, coaches ;))

### CODE REVIEW

**Comment by olasitarska** [comment]
Thanks! :)

**Comment by kvbik** [comment]
Thank you!

On Sunday, April 3, 2016, Ola Sitarska <notifications@github.com> wrote:

> Thanks! :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/DjangoGirls/tutorial/pull/731#issuecomment-204959930>
>


-- 
Jakub Vysoky

mob: +420 605 852 377
jab: jakub.vysoky@gmail.com
twit: https://twitter.com/kvbik

**Comment by tricoder42** [comment]
Sorry for late response! I've been relaxing in Budapest baths :bath: :saxophone: :smile: 

It's actually better to update translations directly in Crowdin, because the workflow is only one-directional. I'll backport these fixes to Crowdin, so we don't loose them later. If you don't have an account on Crowding, I can send you an invite.

Anyway, thank you! :) :rocket: See you soon

**Comment by kvbik** [comment]
ah, cool @tricoder42 good to know. yes, please, send me the invite. btw that is a boomer you cannot edit translations via PRs. hope it is convenient enough to edit all the stuff via crowdin, i will check it out!

**Pull request merged**
