### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by gil9red**
Опечатки

### CODE REVIEW

**Comment by olasitarska** [comment]
@gil9red  would you be able to get someone who speak your language to review these changes and :+1: them here? That would be massively appreciated! :)

**Comment by alexanderad** [comment]
@olasitarska I'm native Russian speaker as well, I can confirm these changes are valid, mainly spelling fixes.

**Comment by olasitarska** [comment]
Perfect, thank you both! :)

**Comment by olasitarska** [comment]
@alexanderad could you also verify #631 and #632?

**Comment by alexanderad** [comment]
@olasitarska will do.

**Comment by gil9red** [comment]
@alexanderad, спасибо, я уже не думал, что изменения примут :)
@olasitarska, please, to me it was not difficult :)

**Pull request merged**
