### PR TITLE
Windows10 error

### PR DESCRIPTION
**Pull request by dns2utf8**
We just made the tutorial on windows an linux in parallel and noticed the command did not work.

### CODE REVIEW

**Comment by brondsem** [comment]
Hm, the original `django-admin.py` works fine for me in Windows 10.  (.exe works too)

**Comment by dns2utf8** [comment]
Interesting, we worked with python 3.6, maybe this is a new bug?

**Comment by aniav** [comment]
`django-admin.py` is deprecated so I am accepting that! :)

**Comment by dns2utf8** [comment]
ah, thank you for searching for the reason.

**Comment by EllekeB** [comment]
For me django-admin.exe does not work, I get the message "access denied" - changing to admin doesn't help, but replacing .exe with .py does work.

**Pull request merged**
