### PR TITLE
Clarify instructions on URLs

### LINKED ISSUE #1335: Getting wrong error in urls.py
### Issue description

I'm attempting to run the tutorial. At the end of the django_urls page, I'm supposed to get an error saying that the post_list view doesn't exist.

But instead I'm getting an error saying 
````
NameError: name 'include' is not defined.
````

When I did a web search on this error, I found that there is a missing line in urls.py:
https://stackoverflow.com/questions/34471102/python-nameerror-name-include-is-not-defined

So I added this line to the top of my urls.py file:
````
from django.conf.urls import include
````

Now I get an error saying 
````
ModuleNotFoundError: No module named 'blog.urls'
````
I have no idea how to proceed now. The tutorial is just not working for me...

### Operating system

I'm running on Windows 8.1 if that makes a difference.

### PR DESCRIPTION
**Pull request by jhodgdon-drp**
Fixes #1335

### CODE REVIEW

**Comment by ekohl** [comment]
This is a longer standing issue. #1165 was about the same thing. In b97aa7cc524eee3863177bff192917a617648044 I changed it to not modify the existing line but explicitly add a new line because that's harder to miss (as suggested by someone else). Looks like this was lost when we migrated the instructions to Django 2.0. Perhaps worth reintroducing?

**Comment by jhodgdon-drp** [comment]
I need to update this PR because we have similar instructions elsewhere for restarting. We should probably make a small .md file that gives the instructions for restarting the web server, and then include it in various places, rather than reinventing it every time it is needed. Anyway, I don't recommend merging just yet...

**Comment by ekohl** [comment]
Thanks!

**Comment by jhodgdon-drp** [comment]
You're welcome! I'm happy to be able to improve the tutorial a bit. :)

**Pull request merged**
