### PR TITLE
Added more installation instructions for Linux.

### PR DESCRIPTION
**Pull request by annlincodemill**
To make it easier to install Python for Linux users. It was a bit unclear on how to proceed after the Python version check.

### CODE REVIEW

**Comment by ekohl** [comment]
This should work on modern distributions that use systemd but may confuse users of older distros where the file doesn't exist. Maybe a guard like "if you don't know which distro" could help but overall I think this is still a good improvement.

**Comment by aniav** [comment]
Yup! You could add the proposed guard before merging, because the way it's phrased now it seems each person *has to* check what distro they have :)

**Comment by ekohl** [comment]
@annlincodemill what do you think about using hostnamectl?
```
ekohl@donald ~ $ hostnamectl status
   Static hostname: donald
         Icon name: computer-desktop
           Chassis: desktop
        Machine ID: ...
           Boot ID: ...
  Operating System: Gentoo/Linux
            Kernel: ...
      Architecture: x86-64
```

Or on Debian:

```
ekohl@bogey ~ $ hostnamectl
   Static hostname: bogey
         Icon name: computer-vm
           Chassis: vm
        Machine ID: ...
           Boot ID: ...
    Virtualization: qemu
  Operating System: Debian GNU/Linux 9 (stretch)
            Kernel: ...
      Architecture: x86-64
```

Or on Fedora:

```
ekohl@wisse ~ $ hostnamectl
   Static hostname: wisse
         Icon name: computer-laptop
           Chassis: laptop
        Machine ID: ...
           Boot ID: ...
  Operating System: Fedora 27 (Workstation Edition)
       CPE OS Name: cpe:/o:fedoraproject:fedora:27
            Kernel: ...
      Architecture: x86-64
```

**Comment by annlincodemill** [comment]
hostnamectl works for me, anything that can improve the guide :)

**Comment by ekohl** [comment]
Would you be willing to update the PR/open a new one to use it?

**Comment by ekohl** [comment]
@annlincodemill it's been a while, but could you have a look?

**Comment by annlincodemill** [comment]
> @annlincodemill it's been a while, but could you have a look?

Yes, I will make an update.

**Comment by das-g** [comment]
To report from a more exotic Linux distribution: On [NixOS](https://nixos.org/)
* `grep ^NAME= /etc/os-release` **works**
  Output:
  ```
  NAME=NixOS

  ```
* `hostnamectl status` **works**
  Output:
  ```
     Static hostname: nixos
           Icon name: computer-laptop
             Chassis: laptop
          Machine ID: 622551e1c9fc4c46b0c91c3cd61be493
             Boot ID: 350d072960c84b1d8b06562f873501e8
    Operating System: NixOS 18.09.1363.b37872d4268 (Jellyfish)
              Kernel: Linux 4.14.81
        Architecture: x86-64
  
  ```
* `lsb_release -a`, another option often recommended for more common distributions **doesn't** work:
  It's not installed by default on NixOS, and if installed, the Output is:
  ```
  LSB Version:	n/a
  Distributor ID:	n/a
  Description:	(none)
  Release:	n/a
  Codename:	n/a
  
  ```

Not that this matters very much for NixOS users. (I doubt many of them don't know what operating system they are using.) But it may give some indication on what works on other less-mainstream Linux distributions.

**Comment by das-g** [comment]
> > @annlincodemill it's been a while, but could you have a look?
> 
> Yes, I will make an update.

Are you still working on that, @annlincodemill?

**Comment by annlincodemill** [comment]
I have now updated the pull request with hostnamectl instead.

**Comment by das-g** [comment]
Um ... please only use merge commits to resolve merge conflicts / fix merge results, not for making further content changes.

**Comment by das-g** [comment]
No sweat, and thanks for your contribution.

Question to others: Can we review and merge it like this, or should the git history be cleaned up, first? If the latter, I can do that this evening <abbr title='central european time: UTC+1'>CET</abbr>, I think.

**Comment by magul** [comment]
@das-g from my perspective I would prefer to have this one commit rebased to the current state of `master` branch. In here the diff looks pretty unreadable. I was able to pull @annlincodemill branch and it occurs that this change is limited to: https://github.com/magul/tutorial/commit/bae28a69394c4186d48c0d22e3834b9d096cd335

Can You @annlincodemill close that pull request and create another one only with that difference?

**Comment by das-g** [comment]
I think the merge commit also contains some changes (coming from neither of the parent branches). I'll try to extract them.

**Comment by das-g** [comment]
Oh, wait, magul@bae28a6 wasn't an existing commit, was it? It's already an attempt to extract the effective changes, I suppose?

**Comment by magul** [comment]
Yes, it is @das-g :)

**Comment by das-g** [comment]
Alright. In https://github.com/DjangoGirls/tutorial/compare/master...das-g:install-python-in-linux, I've
* retained @annlincodemill's original commit fee4a2c
  and
* tried to split the merge-and-some-other-changes commit 2954362 into
  * a clean merge of that commit with 878e280 (`master` back when @annlincodemill did the merge) &rArr; 6480b20
  * two further commits with the rest of the changes: 40b9465 & 49152e8

While this is neither a single commit nor rebased on current `master` this shows a clean diff on GitHub and can currently be merged into `master` without any conflicts.

**Comment by das-g** [comment]
> Can You @annlincodemill close that pull request and create another one only with that difference?

Here are the instructions for creating a pull request with that new set of commits, @annlincodemill:

(If you already have a local clone of the tutorial, you may want to start at step 4 or 5. If you want to use an existing "git remote" to refer to your Fork on GitHub, be sure to adapt the commands after that with the respective remote name.)

1. Open a command line window and `cd` to a location where you want to keep a local copy of the DjangoGirls tutorial repo.
2. Clone the `DjangoGirls/tutorial` repository to your local computer:
   ```bash
   git clone https://github.com/DjangoGirls/tutorial.git
   ```
3. Enter the new local repository:
   ```
   cd tutorial
   ```
4. Add your own GitHub fork as a tracked repository:
   ```bash
   git remote add own https://github.com/annlincodemill/tutorial.git
   ```
5. Add my GitHub fork as a tracked repository:
   ```bash
   git remote add das-g https://github.com/das-g/django-girls-tutorial.git
   ```
6. Fetch my branch `install-python-in-linux` to a new local branch called `determine-linux-distribution`:
   ```bash
   git fetch das-g install-python-in-linux:determine-linux-distribution
   ```
7. Push that new branch to your own GitHub repository:
   ```bash
   git push --set-upstream own determine-linux-distribution
   ```
8. Go to https://github.com/annlincodemill/tutorial/pull/new/determine-linux-distribution and follow the instructions there to create a new pull request from that branch.

**Comment by aniav** [comment]
I managed to rebase all of this and merged it in 7b8f4704180b76ddd44f655b316ff96368863c56. Thank you 🎉

**Pull request closed without merging**
