### PR TITLE
Change `git status` output to reflect no previous commit

### PR DESCRIPTION
**Pull request by nimasmi**
The output from git is given as though a first commit has already been made. This corrects it to show that no commits have been made yet.

### CODE REVIEW

**Comment by magul** [comment]
Hi, thanks for your contribution here!

Unfortunately, there are some conflicts to be resolved here.

**Comment by das-g** [comment]
Isn't this a duplicate of pull request #1578 (which fixed issue #1570 for English)?

That pull request #1578 has already been merged is probably also the reason that there are merge conflicts with this pull request here.

**Comment by nimasmi** [comment]
That might explain it. I pulled from upstream on Saturday, but hadn't seen the changes in #1578. I'll pull again and check.

**Comment by nimasmi** [comment]
I have rebased and force-pushed. Hopefully it's okay now. My editor has added a couple of newline characters at the end of files. I hope that's okay.

**Pull request merged**
