### PR TITLE
change error screen of Korean version.

### PR DESCRIPTION
**Pull request by lexifdev**
Change an error screen for the newer version.

### CODE REVIEW

**Comment by das-g** [comment]
For the textual par of the change, please also suggest that [on Crowdin](https://crowdin.com/translate/django-girls-tutorial/308/en-ko).

**Comment by lexifdev** [comment]
Thank you for your comment.

Then, Can I create a new PR that only replace the Image?

**Comment by das-g** [comment]
> Then, Can I create a new PR that only replace the Image?

No need. We can merge this one when the text changes are also on Crowdin.

**Comment by fltfx** [comment]
closing due to no action

**Pull request closed without merging**
