### PR TITLE
[Spanish] Translation updated and local build

### PR DESCRIPTION
**Pull request by humitos**
This is a work in progress right now. There are a couple of sections that are missing yet.

I'm updating the `es/` folder of the github repository by mixin the latest version from Crowdin (https://crowdin.com/download/project/django-girls-tutorial.zip) and the new sections/changes introduced in the latest `en/` version and also with some fixes that we found in our own workshops.

Besides, I'm building the `es/` website by my own using `gitbook` like this:

```bash
cd es
npm install gitbook-cli
./node_modules/.bin/gitbook install
./node_modules/.bin/gitbook build
```

I'm doing this because It's impossible to get the most updated version of the translation since the source files at Crowdin are outdated. So, my workaround at this moment is to generate the latest version by ourselves.

Please, feel free to add comments/suggestions about how to improve this workflow and let me know if you will consider this PR before I finish my changes.

(I will create another PR with the errors that we found in the `en/` version also)

### CODE REVIEW

**Comment by aniav** [comment]
@DjangoGirls/es-pr can someone review this? :)

**Comment by goanpeca** [comment]
@humitos any chance we can rebase or merge with the latest to fix conflicts?

**Comment by humitos** [comment]
Done!

First I did the merge coming from the latest version of this repository and then I updated the Spanish translation considering the latest updates from the English version.

Hope you approve this PR and merge it!

**Comment by goanpeca** [comment]
>Done!

>First I did the merge coming from the latest version of this repository and then I updated the Spanish translation considering the latest updates from the English version.

>Hope you approve this PR and merge it!

This is awesome che! :-p, I will review and merge as soon as I get back home

**Comment by aniav** [comment]
@goanpeca still willing to review? 👍 Let's get done with it, because these changes are waiting almost a year 😱

**Comment by magul** [comment]
Closing this one in favour of #1397.

**Pull request closed without merging**
