### PR TITLE
[English]: Issue #1179 Match view code

### PR DESCRIPTION
**Pull request by tothebeat**
Changes in this pull request:

Add an argument of `{}` to the `render()` call in the `django_views` portion of the tutorial, to match up to the code referenced in the `dynamic_data_in_templates` portion.

### CODE REVIEW

**Comment by ekohl** [comment]
Shouldn't we simplify ```dynamic_data_in_templates``` instead and only pass in the context when we have context?

**Comment by tothebeat** [comment]
@ekohl That sounds good, that just represents a larger change in all language versions rather than a change in one file for the English version.

**Comment by ekohl** [comment]
@tothebeat it does, but I think the simplicity is worth it. Might be good to get one of the repo owners to state their opinion(s).

**Comment by aniav** [comment]
I think it's ok having the `{}` added as we do fill the context later on in the code. If it would be jus this render used in the whole tutorial I would also suggest removing the empty context.

Thank you! 👍

**Pull request merged**
