### PR TITLE
French typos formatting

### PR DESCRIPTION
**Pull request by ewjoachim**

### CODE REVIEW

**Comment by ewjoachim** [comment]
Yes, my editor automatically removes trailing spaces and adds a final newline when I save. I can try to rebase and remove all these changes if you want.

**Comment by ewjoachim** [comment]
``fr/intro_to_command_line/README.md`` did contain a change unrelated to spaces. It's probably more visible now, I've squashed everything into a single commit and removed all spacing related changes.

**Comment by ewjoachim** [comment]
@ProProgrammer (your comments were on the commits, and I've force-pushed the new history, so they're not visible anymore. I think GitHub handles better comments made on the diffs or in the PR directly...).

**Comment by ProProgrammer** [comment]
That's perfectly fine. Thanks  for taking effort to keep things clean and easy to follow..

**Comment by ewjoachim** [comment]
Thanks for the review :)

**Comment by patjouk** [comment]
Thanks! :sparkles:

**Comment by ewjoachim** [comment]
A real pleasure :cake:

**Pull request merged**
