### PR TITLE
Japanese translation improvements from Crowdin made by:

### PR DESCRIPTION
**Pull request by magul**
* kaizumaki (https://crowdin.com/profile/kaizumaki)

### CODE REVIEW

**Comment by yosu** [comment]
It's almost OK, but a bit mistake was found at `ja/python_introduction/README.md`. 

I have fixed it in Crowdin. Please update the translation.

The difference is:

```diff
- うまくできない時は、質問してください。まさにコーチがここにいるのです！
+ うまくできない時は、質問してください。まさにそのためにコーチがここにいます！
```

**Comment by magul** [comment]
Sorry, I was offline few days. It looks that there were some changes in English version and translation coverage dropped to 95% for Japanese. We should wait till it will 100% again.

**Comment by yosu** [comment]
Oh, I see. I’ll recover it.

**Comment by yosu** [comment]
@magul Thank you!

**Comment by yosu** [comment]
I have reviewed and fixed some translations in Crowdin.

**Comment by magul** [comment]
I've just amended your changes and this commit/pull request should contain them. @yosu

**Pull request merged**
