### PR TITLE
Added Caktus ad

### PR DESCRIPTION
**Pull request by amakarudze**
Changes in this pull request:

- Edited the book.json sidebar ad.
- Added a new ad for Caktus to the sidebar ad.
- Changing sidebar ad normally used for Patreon page or Django Girls store to be a carousel including sponsor ad in the case in the future another sponsor requests this.
- **Note** - Django Girls Foundation Gold and Platinum sponsors have the benefit of an ad in our tutorial if they ask for it. Details are in our [Sponsors Deck](https://drive.google.com/file/d/1QVS4_eWu-cZyvbK5-G0x4sXkDg9Xx6eY/view)

### CODE REVIEW

**Comment by das-g** [comment]
Care to give us some context? Why an add for https://www.caktusgroup.com/ ? Are they e.g. sponsoring the Django Girls foundation?

**Comment by amakarudze** [comment]
> Care to give us some context? Why an add for https://www.caktusgroup.com/ ? Are they e.g. sponsoring the Django Girls foundation?

Yes, they are. We offer this to Gold and Platinum sponsorship levels if the sponsors ask for it and they are the first Gold sponsors to ask for it. Am still figuring out how to make these ads appear as a carousel of some sort.  Let me edit the description of the pull request.

**Comment by amakarudze** [comment]
Hey all, so we have never been requested to do this before but we do have it as part of some of our sponsorship packages, that is, adding a sponsor's ad for a year in our tutorial. I wasn't sure how to do this without removing our own add or how it will appear in our tutorial but if there's a better way to add sponsors' ads please let me know. I am open to suggestions because we may need to do this for more sponsors in the future. Thanks in advance.

**Comment by das-g** [comment]
Sorry, forgot about this.

I guess a change to https://www.npmjs.com/package/gitbook-plugin-sidebar-ad would be needed to support multiple ads.

**Review by das-g — COMMENTED** [review]
As it is now (with addition of commit a09e3a34f8adcd60df682662798e3f9cb61deec1), this PR wouldn't change anything. So unless the forth-and-back changes of the individual commits are for some reason wanted in the repo's history, it can just as well be closed instead of merged.

**Comment by amakarudze** [comment]
> As it is now (with addition of commit [a09e3a3](https://github.com/DjangoGirls/tutorial/commit/a09e3a34f8adcd60df682662798e3f9cb61deec1)), this PR wouldn't change anything. So unless the forth-and-back changes of the individual commits are for some reason wanted in the repo's history, it can just as well be closed instead of merged.

It's long overdue and am now closing it. I need to do some work in the plugin we use for the add so closing it now and implement this when the plugin can support multiple ads.

**Pull request closed without merging**
