### PR TITLE
Pr2

### PR DESCRIPTION
**Pull request by DEVASANA**
Changes in this pull request:

-
-
-

### CODE REVIEW

**Comment by magul** [comment]
Hi @DEVASANA, first of all thank You for your contribution. I would assume that You're working on Tamil translation of tutorial.

From that perspective:
 * your pull request unfortunatelly is unacceptable, as it contains still English version of tutorial instead of anything else (I'm not Tamil language speaker).
 * it would be great if You will apply your potential changes on Crowdin project here: https://crowdin.com/project/django-girls-tutorial/ta#

Using Crowdin will allow us to track changes in English version and apply Tamil update against current English source.

**Comment by DEVASANA** [comment]
Please apologize me for contributed in a wrong way.  I will continue my
translation in the officially recommended way.

**Comment by magul** [comment]
There's no need to apoligize :) If You will have any questions or need any assistance, feel free to ask :)

**Comment by DEVASANA** [comment]
Okie sure....

**Pull request closed without merging**
