### PR TITLE
Fix grammar and tyops

### PR DESCRIPTION
**Pull request by SEJeff**
While going through the tutorial with a few mentees, I spotted a few minor issues. Lets fix them up.

### CODE REVIEW

**Comment by stantonk** [comment]
👍

**Comment by SEJeff** [comment]
Note that the final three commits were directly from things multiple people got caught up on. I'm totally open to removing or rewording things if preferred.

**Comment by stantonk** [comment]
👍

**Comment by helenst** [comment]
Thanks! :whale:

**Pull request merged**
