### PR TITLE
add version to django and whitenoise

### PR DESCRIPTION
**Pull request by v2-dev**
We have specified the version of Django to avoid the default version (1.9)

### CODE REVIEW

**Comment by patjouk** [comment]
Awesome! :sparkles:

**Comment by keimlink** [comment]
Great idea to add version numbers to the `pip install` command. This prevents people from using a wrong version. But the version numbers in the command should match the output below. At the moment `pip install Django==1.8` is used but the output shows `1.8.2`.

**Comment by v2-dev** [comment]
Is 1.8.2 the right version?
Il 12/dic/2015 06:53 PM, "Markus Zapke-Gründemann" <notifications@github.com>
ha scritto:

**Comment by keimlink** [comment]
The latest release of the Django 1.8 series is `1.8.7`.

**Comment by simobasso** [comment]
@keimlink i've used this command right now. The version installed is 1.8... What is your version in `pip list`?

**Comment by v2-dev** [comment]
I personally get that 

(myvenv) viskyria@lamarr:~/django-test$ pip install django==1.8
Downloading/unpacking django==1.8
  Downloading Django-1.8-py2.py3-none-any.whl (6.2MB): 6.2MB downloaded
Installing collected packages: django
Successfully installed django
Cleaning up...
(myvenv) viskyria@lamarr:~/django-test$ django-admin --version
1.8
(myvenv) viskyria@lamarr:~/django-test$ pip list
Django (1.8)
pip (1.5.6)
setuptools (18.7)

**Comment by keimlink** [comment]
If I install Django 1.8 into a fresh virtualenv it looks like that:

    $ pip install Django==1.8
    Collecting Django==1.8
      Downloading Django-1.8-py2.py3-none-any.whl (6.2MB)
        100% |████████████████████████████████| 6.2MB 2.3MB/s
    Installing collected packages: Django
    Successfully installed Django-1.8

    $ pip freeze
    Django==1.8

It always better to use `pip freeze` because it generates a machine-readable output. It also excludes `pip` and `setuptools` from the list.

I'm using pip 7.1.2 with Python 3.5 on OS X 10.10.5.

But `Django==1.8` is not the latest release of the Django 1.8 series. So one should install [Django 1.8.7](https://docs.djangoproject.com/en/1.8/releases/1.8.7/):

    $ pip install Django==1.8.7
    Collecting Django==1.8.7
      Downloading Django-1.8.7-py2.py3-none-any.whl (6.2MB)
        100% |████████████████████████████████| 6.2MB 2.8MB/s
    Installing collected packages: Django
    Successfully installed Django-1.8.7

    $ pip freeze
    Django==1.8.7

I hope this answers your question. If not I'm happy to elaborate my answer. :smile:

**Pull request merged**
