### PR TITLE
DjangoGirls#1570

### PR DESCRIPTION
**Pull request by fernandasj**
Update line 61: 'Initial commit' for 'No commits yet'

### CODE REVIEW

**Comment by magul** [comment]
@fernandasj can you prepare that solution on separate (clean) branch directly from `master`?

Right now it contains also code changes from #1577

**Comment by fernandasj** [comment]
@magul  do I still need to make the new submission or has it been accepted?

**Comment by magul** [comment]
@fernandasj as You already saw in #1577 there are some adjustments to be done, so I would suggest limiting that pull request only to `git status` fix (starting from fresh `master` branch).

**Comment by fernandasj** [comment]
is everything ok now?

**Comment by magul** [comment]
Unfortunately not.

May I suggest to put that `git` change on fresh branch?

To do so:
 * check to current `master`:
```
git checkout master
```
* pull master from upstream
```
git fetch upstream
git merge upstream/master
```
* create new/fresh branch
```
git branch <your-branch-name-here>
```
* checkout to new branch
```
git checkout <your-branch-name-here>
```
* update appriopriate README file
* create new commit
```
git add .
git commit -m"<your commit message>"
```
* push that to your fork
```
git push
```
create new pull request.

**Comment by das-g** [comment]
I've rebased commit e4920be71b52d263ebecfbb593a2af744c6312f2 onto `master` and force-pushed it to [this PR's branch](https://github.com/fernandasj/tutorial/tree/DjangoGirls%231570).

**Pull request merged**
