### PR TITLE
Copy-editing of the English version

### PR DESCRIPTION
**Pull request by logological**
This pull request includes copy-editing for English language issues (fixing grammar, punctuation, unidiomatic language, etc.).  This includes instances of Issue DjangoGirls/tutorial/#793.

### CODE REVIEW

**Comment by aniav** [comment]
Just a note for future, if you happen to change code in some way it would be nice if you could also change its formatting from indentation to fencing. Gitbook prefers this type of markdown code embeding ;)

**Comment by logological** [comment]
OK, I can do that!

**Comment by logological** [comment]
Anna, since I'm going through the entire tutorial, are there any other wide-ranging issues you'd like me to keep an eye out for?  Might as well fix them all at once than make several passes. :)

**Comment by aniav** [comment]
@logological I recall only #375 as a wider thing, but I am not on top of all the issues currently open. Some discussions also appear on our slack, maybe you would like me to invite you there? :)

**Comment by logological** [comment]
Sure, that would be fine.  I expect you still have my e-mail address…?

**Comment by aniav** [comment]
Of course, invitation sent :D

**Comment by aniav** [comment]
@logological give us a sign when you will want this to be merged :)

**Comment by logological** [comment]
I think we can do the merge as soon as I've finished copy-editing all the files.  Once I've done that, should I merge changes from master into this branch and resolve the conflicts myself?  I'm not sure what the etiquette is for this sort of thing, and of course don't want to cause you any extra work.

**Comment by aniav** [comment]
I think until now we asked to resolve the conflicts, but if the PR was hanging for too long afterwards we were resolving them on our side just to keep things clean. So please do resolve the conflicts if that's no problem :)

**Comment by logological** [comment]
OK, finished copy-editing and have resolved conflicts with the current master.  @aniav, please take a look at the pull request and, if you're satisfied with the changes, feel free to merge it into your master branch.

Sorry for taking so long; I had a lot of holidays and business trips the last few weeks so I got distracted. :)

**Comment by aniav** [comment]
Whooow this was a lot of reading and updating. This is awesome! 🎉 🍰 👍

**Pull request merged**
