### PR TITLE
Added Polish translation from crowdin

### PR DESCRIPTION
**Pull request by agagata**
Woo hoo!
Thanks to all the contributors! ✨

### CODE REVIEW

**Comment by patjouk** [comment]
Hi Agata. That's awesome, congratulations!

I checked your PR and realized you've forgot one thing: you need to remove one indent and comment python and html code blocks like [this](https://github.com/DjangoGirls/tutorial/commit/25f093cd2f815704eb03b016845af7d54986e01e#diff-0ce35d3afd321211a71112aa5f36d20aR259). It will add syntax color and prevent learners to copy-past `Python` or `htlm` tags in their code.

**Comment by agagata** [comment]
Lucie, thanks for pointing this out! I don't know why I skipped this step...

**Comment by olasitarska** [comment]
@DjangoGirls/translation-managers anyone has some time to review this?

**Comment by tricoder42** [comment]
@agagata Looks pretty good! :sparkles: Thanks!

**Pull request merged**
