### PR TITLE
Python 3.4.3 fixes

### PR DESCRIPTION
**Pull request by jorisoverzet**
Bump python version to 3.4.3 for spanish and fix the mac os x download link for the different languages.

### CODE REVIEW

**Comment by ProProgrammer** [comment]
Python 3.4.3 not yet supported by Heroku
Here you go: https://devcenter.heroku.com/articles/python-runtimes

**Comment by jorisoverzet** [comment]
@ProProgrammer Could be, but the tutorial already mentioned 3.4.3 since some other pull request, so I just aligned/finished it. If you think it won't work, or it bothers you, write your own pull request to 3.4.2

**Comment by ProProgrammer** [comment]
Actually I had written a pull request myself to update python versions to 3.4.3 (#268) which was first accepted but had to immediately request for reverting the pull request as I later found this Heroku compatibility issue.

Lets hope one of the admins looks into this before merging this pull request

**Comment by jorisoverzet** [comment]
Ok, thank you for the reference. My pullrequest does not touch chapter 11, only the local installation, so this probably won't affect the functionality of deploying on Heroku. But the different versions in local and in requirements.txt could be a little bit confusing for the participant.

**Comment by olasitarska** [comment]
What about this now? We switched from Heroku to PythonAnywhere. Is there still a blocker?

**Comment by aniav** [comment]
PythonAnywhere has 3.4.0 support only. I would close this for now. How do you think?

**Comment by olasitarska** [comment]
@aniav +1

**Pull request closed without merging**
