### PR TITLE
Add visual studio code for code editor

### PR DESCRIPTION
**Pull request by shinecoding**
Changes in this pull request:

- Add visual studio code for code editor

### CODE REVIEW

**Comment by das-g** [comment]
Hi @shinecoding

Thanks for this translation. We manage translations of the Django Girls tutorial [on Crowdin](https://crowdin.com/project/django-girls-tutorial) and already have a translation for this subsection [there](https://crowdin.com/translate/django-girls-tutorial/294/en-ko#13310). Can you check it and either update yours here or the one on Crowdin, so they are the same?

We'd usually sync the Crowdin content of a language to GitHub (from where it'll be deployed to https://tutorial.djangogirls.org) once the translation covers 100% of the original English content. (Syncing earlier would mean to introduce untranslated English sentences into the "translation", which we don't want.) As I somewhat doubt that'll be the case any time soon for the Korean translation, I can offer to merge this PR once its content is in Sync with the subsection translation on Crowdin, so that this translation will be available to users already from then on.

**Comment by das-g** [comment]
(Please comment here once you've brought the translations in this pull request (PR) and on Crowdin in sync.)

**Comment by das-g** [comment]
Re-opening. (Closed #1775 instead.)

**Comment by shinecoding** [comment]
Thanks for letting me know. I checked the link you sent me and sent a pull request for the synced version only for the vs code section. Do you want me to send a pull request for the entire code editor instructions page?
Also, if I want to translate, should I be translating at crowdin instead of sending you pull requests?

**Comment by das-g** [comment]
> Thanks for letting me know. I checked the link you sent me and sent a pull request for the synced version only for the vs code section.

Thanks! As you've pushed your new commits to the same branch, this pull request here got automatically updated. As there was thus no need to have a separate pull request, I've closed #1775 and re-opened this one (#1774).

> Do you want me to send a pull request for the entire code editor instructions page? Also, if I want to translate, should I be translating at crowdin instead of sending you pull requests?

Preferably on Crowdin, as that allows sentence-by-sentence-proofreading (and making individual sentences as proofread) by other translators. (See also #1755.) If you're willing to work on the translation, that's of course very much appreciated!

**Comment by shinecoding** [comment]
From what the previous Korean python community and djangogirls translator have told me is that no one has done any translation for the past 3 years, so I would like to check if the existing translations done in the Crowdin is correct and push it here if that's ok with you?

**Comment by das-g** [comment]
As the English original of the Django Girls tutorial has changed meanwhile, the Korean translation would certainly be out-of-date. However, you don't have to check sentences that Crowdin still displays as already-translated for whether they are up-to-date, as those changed in the original will show up as untranslated. (Even some that actually stayed the same may be shown as untranslated, as Crowdin doesn't always manage to still match them up if another sentence in respective document has changed.) If you yet want to check them for correctness of the translation, feel free to do so.

Preferably though spend your time on translating sentences Crowdin displays as "untranslated". (Often these are sentences that previously had been translated, but were changed in the original since then.) Once the translation for Korean is at 100% on Crowdin, we can export it and update this Git repo accordingly.

**Pull request merged**
