### PR TITLE
Cambio redaccion de nota para aclarar el uso de .

### PR DESCRIPTION
**Pull request by jstitch**
La forma en como estaba el texto no se entendia y quiza estuviera mal traducida.

### CODE REVIEW

**Comment by olasitarska** [comment]
@jstitch would you be able to get someone who speak your language to review these changes and :+1: them here? That would be massively appreciated! :)

**Comment by ctorres-nearsoft** [comment]
:+1:

**Comment by thanniaB** [comment]
:+1:

**Comment by andyosuna** [comment]
👌

**Comment by jstitch** [comment]
@olasitarska cool! here they are ;)

**Comment by olasitarska** [comment]
Thanks! :)

**Comment by FernandaPerez** [comment]
:ok_hand:

**Pull request merged**
