### PR TITLE
Fixing Python Version Link

### PR DESCRIPTION
**Pull request by StephenDonaldson**
Changing URL from 342 to 343 so that it links to version 3.4.3 and not 3.4.2.

### CODE REVIEW

**Comment by ProProgrammer** [comment]
I know it can be tedious but please look for previously created pull requests before submitting a new one.
https://github.com/DjangoGirls/tutorial/pull/279 and https://github.com/DjangoGirls/tutorial/pull/268

**Comment by StephenDonaldson** [comment]
I did; the issue still persists that this is inconsistent with the text afterwards. Either this link needs to be changed or the text after needs to be changed. Currently it's causing confusion for users of the tutorial.

**Comment by ProProgrammer** [comment]
@asendecka Should all such pull requests be closed and instead one be created for change all mentions of Python 3.4.3 to Python 3.4.2 and we keep that consistent at least till heroku starts supporting Python 3.4.3 environment.

Although it doesn't make much of a difference if we have Python 3.4.3 on our local system and 3.4.2 in runtime for heroku but this can be confusing keeping in mind this tutorial is aimed for beginners.

**Comment by aniav** [comment]
I believe we don't have any specification as how such situations should be treated. Until this point most pull requests consisted of a full change. I believe we can just wait a bit until Heroku updates its runtime and then merge both pull requests. Is this a good solution? :)

**Comment by aniav** [comment]
Ok, sorry about me being messy. I am closing this pull request in favour of #279 which has this change and more - it will be cleaner with one PR for this. Thank you!

**Comment by ProProgrammer** [comment]
Very well :+1:

**Comment by ProProgrammer** [comment]
However a pull request has to be submitted to change all references of 3.4.3 to 3.4.2 until Heroku starts supporting python 3.4.3 runtime as I believe people find it confusing to first having to specifically be instructed to install and setup 3.4.3 on their local machines but then be asked to mention 3.4.2 in runtime well at the time of deployment.

**Comment by aniav** [comment]
There i fixed it for you in 83fd4e5 :)

**Comment by ProProgrammer** [comment]
Superb :+1:

**Pull request closed without merging**
