### PR TITLE
Italian translation from Crowdin

### PR DESCRIPTION
**Pull request by magul**
Translation made by:
 * Alessandro Artoni (https://crowdin.com/profile/artoale)
 * Anna Warzecha (vi) (https://crowdin.com/profile/aniav)
 * Annalisa Gioavnnini (https://crowdin.com/profile/Annalisanephila)
 * Arciere (https://crowdin.com/profile/Arciere)
 * Biska (https://crowdin.com/profile/Biska)
 * bobsthinking (https://crowdin.com/profile/bobsthinking)
 * Daniele Catanesi (https://crowdin.com/profile/PsCustomObject)
 * davix3f (https://crowdin.com/profile/davix3f)
 * Denny Biasiolli (https://crowdin.com/profile/dennybiasiolli)
 * DM (https://crowdin.com/profile/DMonty)
 * dynarro (https://crowdin.com/profile/dynarro)
 * enrico ferreguti (https://crowdin.com/profile/enricofer)
 * enrico-giovanni (https://crowdin.com/profile/enrico-giovanni)
 * eracle (https://crowdin.com/profile/eracle)
 * Fabio Bravin (https://crowdin.com/profile/fabio.bravin95)
 * Flavio Curella (https://crowdin.com/profile/fcurella)
 * Giacomo Lanza (https://crowdin.com/profile/nuovog6)
 * giacomo.zanobini (https://crowdin.com/profile/zanoprova)
 * giorgia-amici (https://crowdin.com/profile/giorgia-amici)
 * GiorgioHerbie (https://crowdin.com/profile/GiorgioHerbie)
 * Iacopo Spalletti (https://crowdin.com/profile/yakky)
 * Jeroen Decroos (https://crowdin.com/profile/jeroen.decroos)
 * Marco Acierno (https://crowdin.com/profile/marcoaciernoemail)
 * Marco Burro (https://crowdin.com/profile/marcoburro98)
 * Marianna77 (https://crowdin.com/profile/Marianna77)
 * Mario Frasca (https://crowdin.com/profile/mfrasca)
 * Mattia Procopio (https://crowdin.com/profile/promat85)
 * maupilia (https://crowdin.com/profile/maupilia)
 * Nephila (https://crowdin.com/profile/Nephila)
 * olasitarska (https://crowdin.com/profile/olasitarska)
 * Owly (https://crowdin.com/profile/Owly)
 * Paolo Romolini (https://crowdin.com/profile/romolox)
 * Rebecca Poulson (https://crowdin.com/profile/rapoulson)
 * Riccardo Magliocchetti (https://crowdin.com/profile/xrmx)
 * Sara Zappaterra (https://crowdin.com/profile/SaraZ82)
 * Sergio (https://crowdin.com/profile/sgio65)
 * Silviu-Dumitru Paduraru (https://crowdin.com/profile/Silviu93)
 * Solitary90 (https://crowdin.com/profile/Solitary90)
 * Tania Monti (https://crowdin.com/profile/tania_monti)
 * Vale88 (https://crowdin.com/profile/Vale88)
 * Valerio Ragni (https://crowdin.com/profile/ragni.valerio)

### CODE REVIEW

**Comment by C8E** [comment]
:+1: :tada:

**Comment by magul** [comment]
Hi @C8E, does it mean that I can merge it or do you want to spend some more time reviewing it?

**Comment by C8E** [comment]
> Hi @C8E, does it mean that I can merge it or do you want to spend some more time reviewing it?

no time for a full review in the foreseeable future, sorry. but at a quick glance it seems an improvement to me. @yakky whatcha think?

**Comment by magul** [comment]
So @C8E , based on your opinion about improvement, I will wait for a week and if there will not be any objections (from you or any other Italian native speaker, like @yakky) I will merge it.

**Pull request merged**
